import type { CancelP2PSwapResponse, ChitEventsRequest, ChitEventsResponse, ClaimDailyChitResponse, JoinVideoCallResponse, MessageActivityFeedResponse, SetPinNumberResponse, SetVideoCallPresenceResponse, Verification, VideoCallPresence, WalletConfig } from "openchat-shared";
import type { AcceptP2PSwapResponse } from "openchat-shared";
import type { InitialStateResponse, UpdatesResponse, EventsResponse, CandidateGroupChat, CreateGroupResponse, DeleteGroupResponse, ChatEvent, Message, SendMessageResponse, BlockUserResponse, UnblockUserResponse, LeaveGroupResponse, MarkReadResponse, IndexRange, AddRemoveReactionResponse, DeleteMessageResponse, UndeleteMessageResponse, EditMessageResponse, MarkReadRequest, WithdrawCryptocurrencyResponse, PendingCryptocurrencyWithdrawal, ArchiveChatResponse, BlobReference, CreatedUser, PinChatResponse, PublicProfile, SearchDirectChatResponse, SetBioResponse, ToggleMuteNotificationResponse, UnpinChatResponse, DeletedDirectMessageResponse, EventWrapper, SetMessageReminderResponse, CommunitySummary, CreateCommunityResponse, ChatIdentifier, DirectChatIdentifier, GroupChatIdentifier, ManageFavouritesResponse, CommunityIdentifier, LeaveCommunityResponse, DeleteCommunityResponse, ChannelIdentifier, Rules, TipMessageResponse, NamedAccount, SaveCryptoAccountResponse, CandidateProposal, SubmitProposalResponse, MessageContext, PendingCryptocurrencyTransfer, CryptocurrencyDetails, ExchangeTokenSwapArgs, SwapTokensResponse, TokenSwapStatusResponse, ApproveTransferResponse } from "openchat-shared";
export declare class AnonUserClient {
    get userId(): string;
    static create(): AnonUserClient;
    manageFavouriteChats(_toAdd: ChatIdentifier[], _toRemove: ChatIdentifier[]): Promise<ManageFavouritesResponse>;
    getInitialState(): Promise<InitialStateResponse>;
    getUpdates(_updatesSince: bigint): Promise<UpdatesResponse>;
    createCommunity(_community: CommunitySummary, _rules: Rules, _defaultChannels: string[], _defaultChannelRules: Rules): Promise<CreateCommunityResponse>;
    createGroup(_group: CandidateGroupChat): Promise<CreateGroupResponse>;
    deleteGroup(_chatId: string): Promise<DeleteGroupResponse>;
    deleteCommunity(_id: CommunityIdentifier): Promise<DeleteCommunityResponse>;
    getCachedEventsByIndex(_eventIndexes: number[], _chatId: DirectChatIdentifier, _threadRootMessageIndex: number | undefined): Promise<[EventsResponse<ChatEvent>, Set<number>]>;
    chatEventsByIndex(_eventIndexes: number[], _chatId: DirectChatIdentifier, _threadRootMessageIndex: number | undefined, _latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    chatEventsWindow(_eventIndexRange: IndexRange, _chatId: DirectChatIdentifier, _messageIndex: number, _latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    chatEvents(_eventIndexRange: IndexRange, _chatId: DirectChatIdentifier, _startIndex: number, _ascending: boolean, _threadRootMessageIndex: number | undefined, _latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    setAvatar(_bytes: Uint8Array): Promise<BlobReference>;
    editMessage(_recipientId: string, _message: Message, _threadRootMessageIndex?: number): Promise<EditMessageResponse>;
    sendMessage(_chatId: DirectChatIdentifier, _event: EventWrapper<Message>, _messageFilterFailed: bigint | undefined, _threadRootMessageIndex: number | undefined, _pin: string | undefined, _onRequestAccepted: () => void): Promise<[SendMessageResponse, Message]>;
    sendMessageToBackend(_chatId: DirectChatIdentifier, _event: EventWrapper<Message>, _threadRootMessageIndex?: number): Promise<[SendMessageResponse, Message]>;
    sendMessageWithTransferToGroup(_groupId: GroupChatIdentifier, _recipientId: string | undefined, _sender: CreatedUser, _event: EventWrapper<Message>, _threadRootMessageIndex: number | undefined, _rulesAccepted: number | undefined): Promise<[SendMessageResponse, Message]>;
    loadSavedCryptoAccounts(): Promise<NamedAccount[]>;
    saveCryptoAccount(_: NamedAccount): Promise<SaveCryptoAccountResponse>;
    sendMessageWithTransferToChannel(_id: ChannelIdentifier, _recipientId: string | undefined, _sender: CreatedUser, _event: EventWrapper<Message>, _threadRootMessageIndex: number | undefined, _communityRulesAccepted: number | undefined, _channelRulesAccepted: number | undefined): Promise<[SendMessageResponse, Message]>;
    blockUser(_userId: string): Promise<BlockUserResponse>;
    unblockUser(_userId: string): Promise<UnblockUserResponse>;
    leaveGroup(_chatId: string): Promise<LeaveGroupResponse>;
    leaveCommunity(_id: CommunityIdentifier): Promise<LeaveCommunityResponse>;
    markMessagesRead(_request: MarkReadRequest): Promise<MarkReadResponse>;
    tipMessage(_messageContext: MessageContext, _messageId: bigint, _transfer: PendingCryptocurrencyTransfer, _decimals: number, _pin: string | undefined): Promise<TipMessageResponse>;
    addReaction(_otherUserId: string, _messageId: bigint, _reaction: string, _threadRootMessageIndex?: number): Promise<AddRemoveReactionResponse>;
    removeReaction(_otherUserId: string, _messageId: bigint, _reaction: string, _threadRootMessageIndex?: number): Promise<AddRemoveReactionResponse>;
    deleteMessage(_otherUserId: string, _messageId: bigint, _threadRootMessageIndex?: number): Promise<DeleteMessageResponse>;
    undeleteMessage(_otherUserId: string, _messageId: bigint, _threadRootMessageIndex?: number): Promise<UndeleteMessageResponse>;
    searchDirectChat(_chatId: DirectChatIdentifier, _searchTerm: string, _maxResults: number): Promise<SearchDirectChatResponse>;
    toggleMuteNotifications(_chatId: string, _muted: boolean): Promise<ToggleMuteNotificationResponse>;
    dismissRecommendation(_chatId: string): Promise<void>;
    getBio(): Promise<string>;
    getPublicProfile(): Promise<PublicProfile>;
    setBio(_bio: string): Promise<SetBioResponse>;
    withdrawCryptocurrency(_domain: PendingCryptocurrencyWithdrawal): Promise<WithdrawCryptocurrencyResponse>;
    pinChat(_chatId: ChatIdentifier, _favourite: boolean): Promise<PinChatResponse>;
    unpinChat(_chatId: ChatIdentifier, _favourite: boolean): Promise<UnpinChatResponse>;
    archiveChat(_chatId: ChatIdentifier): Promise<ArchiveChatResponse>;
    unarchiveChat(_chatId: ChatIdentifier): Promise<ArchiveChatResponse>;
    getDeletedMessage(_userId: string, _messageId: bigint): Promise<DeletedDirectMessageResponse>;
    setMessageReminder(_chatId: ChatIdentifier, _eventIndex: number, _remindAt: number, _notes?: string, _threadRootMessageIndex?: number): Promise<SetMessageReminderResponse>;
    cancelMessageReminder(_reminderId: bigint): Promise<boolean>;
    setCommunityIndexes(_communityIndexes: Record<string, number>): Promise<boolean>;
    submitProposal(_governanceCanisterId: string, _proposal: CandidateProposal, _ledger: string, _token: string, _proposalRejectionFee: bigint, _transactionFee: bigint): Promise<SubmitProposalResponse>;
    reportMessage(_chatId: DirectChatIdentifier, _threadRootMessageIndex: number | undefined, _messageId: bigint, _deleteMessage: boolean): Promise<boolean>;
    swapTokens(_swapId: bigint, _inputToken: CryptocurrencyDetails, _outputToken: CryptocurrencyDetails, _amountIn: bigint, _minAmountOut: bigint, _exchangeArgs: ExchangeTokenSwapArgs): Promise<SwapTokensResponse>;
    tokenSwapStatus(_swapId: bigint): Promise<TokenSwapStatusResponse>;
    approveTransfer(_spender: string, _ledger: string, _amount: bigint, _expiresIn: bigint | undefined): Promise<ApproveTransferResponse>;
    deleteDirectChat(_userId: string, _blockUser: boolean): Promise<boolean>;
    acceptP2PSwap(_userId: string, _threadRootMessageIndex: number | undefined, _messageId: bigint, _pin: string | undefined): Promise<AcceptP2PSwapResponse>;
    cancelP2PSwap(_userId: string, _messageId: bigint): Promise<CancelP2PSwapResponse>;
    joinVideoCall(_userId: string, _messageId: bigint): Promise<JoinVideoCallResponse>;
    setVideoCallPresence(_messageId: bigint, _presence: VideoCallPresence): Promise<SetVideoCallPresenceResponse>;
    localUserIndex(): Promise<string>;
    setPinNumber(_verification: Verification, _newPin: string | undefined): Promise<SetPinNumberResponse>;
    chitEvents(_req: ChitEventsRequest): Promise<ChitEventsResponse>;
    markAchievementsSeen(_lastSeen: bigint): Promise<void>;
    claimDailyChit(): Promise<ClaimDailyChitResponse>;
    configureWallet(_walletConfig: WalletConfig): Promise<void>;
    markActivityFeedRead(_timestamp: bigint): Promise<void>;
    messageActivityFeed(_since: bigint): Promise<MessageActivityFeedResponse>;
}
