import type { Achievement as TAchievement, Chat as TChat, ChitEarned as TChitEarned, ChitEarnedReason as TChitEarnedReason, ProposalsBotProposalToSubmit, ReferralStatus as TReferralStatus, UserApproveTransferResponse, UserArchiveUnarchiveChatsResponse, UserChannelSummaryUpdates, UserChitEventsResponse, UserClaimDailyChitResponse, UserCommunitySummaryUpdates, UserCreateCommunityResponse, UserDeleteCommunityResponse, UserDeletedMessageResponse, UserDeleteMessagesResponse, UserEventsResponse, UserInitialStateResponse, UserLeaveCommunityResponse, UserManageFavouriteChatsResponse, UserPinChatResponse, UserPublicProfileResponse, UserReportMessageResponse, UserSaveCryptoAccountResponse, UserSavedCryptoAccountsResponse, UserSearchMessagesResponse, UserSendMessageResponse, UserSendMessageWithTransferToChannelResponse, UserSendMessageWithTransferToGroupResponse, UserSetAvatarResponse, UserSetBioResponse, UserSetMessageReminderResponse, UserSetPinNumberPinNumberVerification, UserSubmitProposalResponse, UserSwapTokensExchangeArgs, UserSwapTokensResponse, UserTipMessageResponse, UserTokenSwapStatusResponse, UserUndeleteMessagesResponse, UserUnpinChatResponse, UserUpdatesCommunitiesUpdates, UserUpdatesDirectChatsUpdates, UserUpdatesFavouriteChatsUpdates, UserUpdatesGroupChatsUpdates, UserUpdatesResponse, UserWalletConfig, UserWithdrawCryptoResponse, UserMessageActivityFeedResponse, UserMessageActivityEvent, UserMessageActivity } from "../../typebox";
import type { EventsResponse, ChatEvent, SendMessageResponse, SetAvatarResponse, DeleteMessageResponse, UndeleteMessageResponse, InitialStateResponse, UpdatesResponse, WithdrawCryptocurrencyResponse, PublicProfile, ArchiveChatResponse, PinChatResponse, SearchDirectChatResponse, SetBioResponse, DeletedDirectMessageResponse, SetMessageReminderResponse, CreateCommunityResponse, CommunitiesUpdates, UserCanisterCommunitySummaryUpdates, UserCanisterChannelSummaryUpdates, FavouriteChatsUpdates, GroupChatsUpdates, DirectChatsUpdates, DirectChatIdentifier, ManageFavouritesResponse, LeaveCommunityResponse, DeleteCommunityResponse, TipMessageResponse, NamedAccount, SaveCryptoAccountResponse, CandidateProposal, SubmitProposalResponse, SwapTokensResponse, TokenSwapStatusResponse, ApproveTransferResponse, ExchangeTokenSwapArgs, ChitEventsResponse, ChitEarned, ChitEarnedReason, Achievement, ClaimDailyChitResponse, ReferralStatus, WalletConfig, Verification, MessageActivityFeedResponse, MessageActivityEvent, MessageContext, MessageActivity } from "openchat-shared";
import { Principal } from "@dfinity/principal";
export declare function messageActivityFeedResponse(value: UserMessageActivityFeedResponse): MessageActivityFeedResponse;
export declare function messageActivityEvent(value: UserMessageActivityEvent): MessageActivityEvent;
export declare function messageContext(chat: TChat, threadRootMessageIndex: number | undefined): MessageContext;
export declare function messageActivity(value: UserMessageActivity): MessageActivity;
export declare function chitEventsResponse(value: UserChitEventsResponse): ChitEventsResponse;
export declare function chitEarned(value: TChitEarned): ChitEarned;
export declare function chitEarnedReason(value: TChitEarnedReason): ChitEarnedReason;
export declare function referralStatus(value: TReferralStatus): ReferralStatus;
export declare function achievementType(value: TAchievement): Achievement;
export declare function saveCryptoAccountResponse(value: UserSaveCryptoAccountResponse): SaveCryptoAccountResponse;
export declare function savedCryptoAccountsResponse(value: UserSavedCryptoAccountsResponse): NamedAccount[];
export declare function tipMessageResponse(value: UserTipMessageResponse): TipMessageResponse;
export declare function publicProfileResponse(value: UserPublicProfileResponse): PublicProfile;
export declare function setBioResponse(value: UserSetBioResponse): SetBioResponse;
export declare function searchDirectChatResponse(value: UserSearchMessagesResponse, chatId: DirectChatIdentifier): SearchDirectChatResponse;
export declare function deleteMessageResponse(value: UserDeleteMessagesResponse): DeleteMessageResponse;
export declare function undeleteMessageResponse(value: UserUndeleteMessagesResponse): UndeleteMessageResponse;
export declare function setAvatarResponse(value: UserSetAvatarResponse): SetAvatarResponse;
export declare function pinChatResponse(value: UserPinChatResponse | UserUnpinChatResponse): PinChatResponse;
export declare function archiveChatResponse(value: UserArchiveUnarchiveChatsResponse): ArchiveChatResponse;
export declare function sendMessageWithTransferToChannelResponse(value: UserSendMessageWithTransferToChannelResponse, sender: string, recipient: string | undefined): SendMessageResponse;
export declare function sendMessageWithTransferToGroupResponse(value: UserSendMessageWithTransferToGroupResponse, sender: string, recipient: string | undefined): SendMessageResponse;
export declare function sendMessageResponse(value: UserSendMessageResponse, sender: string, recipient: string): SendMessageResponse;
export declare function createCommunityResponse(value: UserCreateCommunityResponse): CreateCommunityResponse;
export declare function getEventsResponse(principal: Principal, value: UserEventsResponse, chatId: DirectChatIdentifier, latestKnownUpdatePreRequest: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
export declare function initialStateResponse(value: UserInitialStateResponse): InitialStateResponse;
export declare function apiWalletConfig(domain: WalletConfig): UserWalletConfig;
export declare function userCanisterChannelSummaryUpdates(value: UserChannelSummaryUpdates, communityId: string): UserCanisterChannelSummaryUpdates;
export declare function userCanisterCommunitySummaryUpdates(value: UserCommunitySummaryUpdates): UserCanisterCommunitySummaryUpdates;
export declare function communitiesUpdates(value: UserUpdatesCommunitiesUpdates): CommunitiesUpdates;
export declare function favouriteChatsUpdates(value: UserUpdatesFavouriteChatsUpdates): FavouriteChatsUpdates;
export declare function groupChatsUpdates(value: UserUpdatesGroupChatsUpdates): GroupChatsUpdates;
export declare function directChatsUpdates(value: UserUpdatesDirectChatsUpdates): DirectChatsUpdates;
export declare function manageFavouritesResponse(value: UserManageFavouriteChatsResponse): ManageFavouritesResponse;
export declare function getUpdatesResponse(value: UserUpdatesResponse): UpdatesResponse;
export declare function withdrawCryptoResponse(value: UserWithdrawCryptoResponse): WithdrawCryptocurrencyResponse;
export declare function deletedMessageResponse(value: UserDeletedMessageResponse): DeletedDirectMessageResponse;
export declare function setMessageReminderResponse(value: UserSetMessageReminderResponse): SetMessageReminderResponse;
export declare function leaveCommunityResponse(value: UserLeaveCommunityResponse): LeaveCommunityResponse;
export declare function deleteCommunityResponse(value: UserDeleteCommunityResponse): DeleteCommunityResponse;
export declare function proposalToSubmit(proposal: CandidateProposal): ProposalsBotProposalToSubmit;
export declare function submitProposalResponse(value: UserSubmitProposalResponse): SubmitProposalResponse;
export declare function reportMessageResponse(value: UserReportMessageResponse): boolean;
export declare function swapTokensResponse(value: UserSwapTokensResponse): SwapTokensResponse;
export declare function tokenSwapStatusResponse(value: UserTokenSwapStatusResponse): TokenSwapStatusResponse;
export declare function approveTransferResponse(value: UserApproveTransferResponse): ApproveTransferResponse;
export declare function apiExchangeArgs(args: ExchangeTokenSwapArgs): UserSwapTokensExchangeArgs;
export declare function claimDailyChitResponse(value: UserClaimDailyChitResponse): ClaimDailyChitResponse;
export declare function apiVerification(domain: Verification): UserSetPinNumberPinNumberVerification;
