import type { HttpAgent, Identity } from "@dfinity/agent";
import type { InitialStateResponse, UpdatesResponse, EventsResponse, CandidateGroupChat, CreateGroupResponse, DeleteGroupResponse, Message, SendMessageResponse, BlockUserResponse, UnblockUserResponse, LeaveGroupResponse, MarkReadResponse, IndexRange, AddRemoveReactionResponse, DeleteMessageResponse, UndeleteMessageResponse, EditMessageResponse, MarkReadRequest, WithdrawCryptocurrencyResponse, PendingCryptocurrencyWithdrawal, ArchiveChatResponse, BlobReference, CreatedUser, PinChatResponse, PublicProfile, SearchDirectChatResponse, SetBioResponse, ToggleMuteNotificationResponse, UnpinChatResponse, DeletedDirectMessageResponse, EventWrapper, SetMessageReminderResponse, ChatEvent, EventsSuccessResult, CommunitySummary, CreateCommunityResponse, ChatIdentifier, DirectChatIdentifier, GroupChatIdentifier, ManageFavouritesResponse, CommunityIdentifier, LeaveCommunityResponse, DeleteCommunityResponse, ChannelIdentifier, Rules, TipMessageResponse, NamedAccount, SaveCryptoAccountResponse, CandidateProposal, SubmitProposalResponse, CryptocurrencyDetails, ExchangeTokenSwapArgs, SwapTokensResponse, TokenSwapStatusResponse, ApproveTransferResponse, MessageContext, PendingCryptocurrencyTransfer, AcceptP2PSwapResponse, CancelP2PSwapResponse, JoinVideoCallResponse, ChitEventsRequest, ChitEventsResponse, ClaimDailyChitResponse, WalletConfig, Verification, MessageActivityFeedResponse } from "openchat-shared";
import { CandidService } from "../candidService";
import { type Database } from "../../utils/caching";
import type { AgentConfig } from "../../config";
import type { SetPinNumberResponse } from "openchat-shared";
export declare class UserClient extends CandidService {
    private config;
    private db;
    userId: string;
    private chatId;
    constructor(userId: string, identity: Identity, agent: HttpAgent, config: AgentConfig, db: Database);
    private setCachedEvents;
    private handleMissingEvents;
    manageFavouriteChats(toAdd: ChatIdentifier[], toRemove: ChatIdentifier[]): Promise<ManageFavouritesResponse>;
    getInitialState(): Promise<InitialStateResponse>;
    getUpdates(updatesSince: bigint): Promise<UpdatesResponse>;
    createCommunity(community: CommunitySummary, rules: Rules, defaultChannels: string[], defaultChannelRules: Rules): Promise<CreateCommunityResponse>;
    createGroup(group: CandidateGroupChat): Promise<CreateGroupResponse>;
    deleteGroup(chatId: string): Promise<DeleteGroupResponse>;
    deleteCommunity(id: CommunityIdentifier): Promise<DeleteCommunityResponse>;
    getCachedEventsByIndex(eventIndexes: number[], chatId: DirectChatIdentifier, threadRootMessageIndex: number | undefined): Promise<[EventsSuccessResult<ChatEvent>, Set<number>]>;
    chatEventsByIndex(eventIndexes: number[], chatId: DirectChatIdentifier, threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    private chatEventsByIndexFromBackend;
    chatEventsWindow(eventIndexRange: IndexRange, chatId: DirectChatIdentifier, messageIndex: number, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    private chatEventsWindowFromBackend;
    chatEvents(eventIndexRange: IndexRange, chatId: DirectChatIdentifier, startIndex: number, ascending: boolean, threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    private chatEventsFromBackend;
    setAvatar(bytes: Uint8Array): Promise<BlobReference>;
    editMessage(recipientId: string, message: Message, threadRootMessageIndex?: number, blockLevelMarkdown?: boolean): Promise<EditMessageResponse>;
    sendMessage(chatId: DirectChatIdentifier, event: EventWrapper<Message>, messageFilterFailed: bigint | undefined, threadRootMessageIndex: number | undefined, pin: string | undefined, onRequestAccepted: () => void): Promise<[SendMessageResponse, Message]>;
    sendMessageToBackend(chatId: DirectChatIdentifier, event: EventWrapper<Message>, messageFilterFailed: bigint | undefined, threadRootMessageIndex: number | undefined, pin: string | undefined, onRequestAccepted: () => void): Promise<[SendMessageResponse, Message]>;
    sendMessageWithTransferToGroup(groupId: GroupChatIdentifier, recipientId: string | undefined, sender: CreatedUser, event: EventWrapper<Message>, threadRootMessageIndex: number | undefined, rulesAccepted: number | undefined, messageFilterFailed: bigint | undefined, pin: string | undefined): Promise<[SendMessageResponse, Message]>;
    private sendMessageWithTransferToGroupToBackend;
    loadSavedCryptoAccounts(): Promise<NamedAccount[]>;
    saveCryptoAccount({ name, account }: NamedAccount): Promise<SaveCryptoAccountResponse>;
    sendMessageWithTransferToChannel(id: ChannelIdentifier, recipientId: string | undefined, sender: CreatedUser, event: EventWrapper<Message>, threadRootMessageIndex: number | undefined, communityRulesAccepted: number | undefined, channelRulesAccepted: number | undefined, messageFilterFailed: bigint | undefined, pin: string | undefined): Promise<[SendMessageResponse, Message]>;
    private sendMessageWithTransferToChannelToBackend;
    blockUser(userId: string): Promise<BlockUserResponse>;
    unblockUser(userId: string): Promise<UnblockUserResponse>;
    leaveGroup(chatId: string): Promise<LeaveGroupResponse>;
    leaveCommunity(id: CommunityIdentifier): Promise<LeaveCommunityResponse>;
    private markMessageArg;
    private markChannelMessageArg;
    private markMessageArgs;
    markMessagesRead(request: MarkReadRequest): Promise<MarkReadResponse>;
    tipMessage(messageContext: MessageContext, messageId: bigint, transfer: PendingCryptocurrencyTransfer, decimals: number, pin: string | undefined): Promise<TipMessageResponse>;
    addReaction(otherUserId: string, messageId: bigint, reaction: string, threadRootMessageIndex: number | undefined): Promise<AddRemoveReactionResponse>;
    removeReaction(otherUserId: string, messageId: bigint, reaction: string, threadRootMessageIndex?: number): Promise<AddRemoveReactionResponse>;
    deleteMessage(otherUserId: string, messageId: bigint, threadRootMessageIndex?: number): Promise<DeleteMessageResponse>;
    undeleteMessage(otherUserId: string, messageId: bigint, threadRootMessageIndex?: number): Promise<UndeleteMessageResponse>;
    searchDirectChat(chatId: DirectChatIdentifier, searchTerm: string, maxResults: number): Promise<SearchDirectChatResponse>;
    toggleMuteNotifications(chatId: string, muted: boolean): Promise<ToggleMuteNotificationResponse>;
    dismissRecommendation(chatId: string): Promise<void>;
    getBio(): Promise<string>;
    getPublicProfile(): Promise<PublicProfile>;
    setBio(bio: string): Promise<SetBioResponse>;
    withdrawCryptocurrency(domain: PendingCryptocurrencyWithdrawal, pin: string | undefined): Promise<WithdrawCryptocurrencyResponse>;
    private toChatInList;
    pinChat(chatId: ChatIdentifier, favourite: boolean): Promise<PinChatResponse>;
    unpinChat(chatId: ChatIdentifier, favourite: boolean): Promise<UnpinChatResponse>;
    archiveChat(chatId: ChatIdentifier): Promise<ArchiveChatResponse>;
    unarchiveChat(chatId: ChatIdentifier): Promise<ArchiveChatResponse>;
    getDeletedMessage(userId: string, messageId: bigint): Promise<DeletedDirectMessageResponse>;
    setMessageReminder(chatId: ChatIdentifier, eventIndex: number, remindAt: number, notes?: string, threadRootMessageIndex?: number): Promise<SetMessageReminderResponse>;
    cancelMessageReminder(reminderId: bigint): Promise<boolean>;
    setCommunityIndexes(communityIndexes: Record<string, number>): Promise<boolean>;
    submitProposal(governanceCanisterId: string, proposal: CandidateProposal, ledger: string, token: string, proposalRejectionFee: bigint, transactionFee: bigint): Promise<SubmitProposalResponse>;
    reportMessage(chatId: DirectChatIdentifier, threadRootMessageIndex: number | undefined, messageId: bigint, deleteMessage: boolean): Promise<boolean>;
    swapTokens(swapId: bigint, inputToken: CryptocurrencyDetails, outputToken: CryptocurrencyDetails, amountIn: bigint, minAmountOut: bigint, exchangeArgs: ExchangeTokenSwapArgs, pin: string | undefined): Promise<SwapTokensResponse>;
    tokenSwapStatus(swapId: bigint): Promise<TokenSwapStatusResponse>;
    approveTransfer(spender: string, ledger: string, amount: bigint, expiresIn: bigint | undefined, pin: string | undefined): Promise<ApproveTransferResponse>;
    deleteDirectChat(userId: string, blockUser: boolean): Promise<boolean>;
    acceptP2PSwap(userId: string, threadRootMessageIndex: number | undefined, messageId: bigint, pin: string | undefined): Promise<AcceptP2PSwapResponse>;
    cancelP2PSwap(userId: string, messageId: bigint): Promise<CancelP2PSwapResponse>;
    joinVideoCall(userId: string, messageId: bigint): Promise<JoinVideoCallResponse>;
    localUserIndex(): Promise<string>;
    setPinNumber(verification: Verification, newPin: string | undefined): Promise<SetPinNumberResponse>;
    chitEvents({ from, to, max, ascending }: ChitEventsRequest): Promise<ChitEventsResponse>;
    markAchievementsSeen(lastSeen: bigint): Promise<void>;
    claimDailyChit(): Promise<ClaimDailyChitResponse>;
    configureWallet(walletConfig: WalletConfig): Promise<void>;
    markActivityFeedRead(readUpTo: bigint): Promise<void>;
    messageActivityFeed(since: bigint): Promise<MessageActivityFeedResponse>;
}
