"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Notification = void 0;
const candid_1 = require("@dfinity/candid");
exports.Notification = candid_1.IDL.Variant({
    'GroupReactionAdded': candid_1.IDL.Record({
        'added_by_name': candid_1.IDL.Text,
        'group_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'message_event_index': candid_1.IDL.Nat32,
        'added_by': candid_1.IDL.Principal,
        'added_by_display_name': candid_1.IDL.Opt(candid_1.IDL.Text),
        'chat_id': candid_1.IDL.Principal,
        'thread_root_message_index': candid_1.IDL.Opt(candid_1.IDL.Nat32),
        'group_name': candid_1.IDL.Text,
        'reaction': candid_1.IDL.Text,
        'message_index': candid_1.IDL.Nat32,
    }),
    'ChannelMessageTipped': candid_1.IDL.Record({
        'tip': candid_1.IDL.Text,
        'channel_id': candid_1.IDL.Nat,
        'tipped_by_display_name': candid_1.IDL.Opt(candid_1.IDL.Text),
        'community_id': candid_1.IDL.Principal,
        'message_event_index': candid_1.IDL.Nat32,
        'channel_name': candid_1.IDL.Text,
        'tipped_by': candid_1.IDL.Principal,
        'community_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'community_name': candid_1.IDL.Text,
        'tipped_by_name': candid_1.IDL.Text,
        'thread_root_message_index': candid_1.IDL.Opt(candid_1.IDL.Nat32),
        'channel_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'message_index': candid_1.IDL.Nat32,
    }),
    'DirectMessageTipped': candid_1.IDL.Record({
        'tip': candid_1.IDL.Text,
        'username': candid_1.IDL.Text,
        'message_event_index': candid_1.IDL.Nat32,
        'them': candid_1.IDL.Principal,
        'display_name': candid_1.IDL.Opt(candid_1.IDL.Text),
        'user_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'thread_root_message_index': candid_1.IDL.Opt(candid_1.IDL.Nat32),
        'message_index': candid_1.IDL.Nat32,
    }),
    'DirectMessage': candid_1.IDL.Record({
        'image_url': candid_1.IDL.Opt(candid_1.IDL.Text),
        'sender_display_name': candid_1.IDL.Opt(candid_1.IDL.Text),
        'sender_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'sender': candid_1.IDL.Principal,
        'sender_name': candid_1.IDL.Text,
        'message_text': candid_1.IDL.Opt(candid_1.IDL.Text),
        'message_type': candid_1.IDL.Text,
        'event_index': candid_1.IDL.Nat32,
        'thread_root_message_index': candid_1.IDL.Opt(candid_1.IDL.Nat32),
        'crypto_transfer': candid_1.IDL.Opt(candid_1.IDL.Record({
            'recipient': candid_1.IDL.Principal,
            'ledger': candid_1.IDL.Principal,
            'recipient_username': candid_1.IDL.Opt(candid_1.IDL.Text),
            'amount': candid_1.IDL.Nat,
            'symbol': candid_1.IDL.Text,
        })),
        'message_index': candid_1.IDL.Nat32,
    }),
    'ChannelReactionAdded': candid_1.IDL.Record({
        'channel_id': candid_1.IDL.Nat,
        'community_id': candid_1.IDL.Principal,
        'added_by_name': candid_1.IDL.Text,
        'message_event_index': candid_1.IDL.Nat32,
        'added_by': candid_1.IDL.Principal,
        'channel_name': candid_1.IDL.Text,
        'community_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'added_by_display_name': candid_1.IDL.Opt(candid_1.IDL.Text),
        'community_name': candid_1.IDL.Text,
        'thread_root_message_index': candid_1.IDL.Opt(candid_1.IDL.Nat32),
        'channel_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'reaction': candid_1.IDL.Text,
        'message_index': candid_1.IDL.Nat32,
    }),
    'DirectReactionAdded': candid_1.IDL.Record({
        'username': candid_1.IDL.Text,
        'message_event_index': candid_1.IDL.Nat32,
        'them': candid_1.IDL.Principal,
        'display_name': candid_1.IDL.Opt(candid_1.IDL.Text),
        'user_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'thread_root_message_index': candid_1.IDL.Opt(candid_1.IDL.Nat32),
        'reaction': candid_1.IDL.Text,
        'message_index': candid_1.IDL.Nat32,
    }),
    'GroupMessage': candid_1.IDL.Record({
        'image_url': candid_1.IDL.Opt(candid_1.IDL.Text),
        'group_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'sender_display_name': candid_1.IDL.Opt(candid_1.IDL.Text),
        'sender': candid_1.IDL.Principal,
        'sender_name': candid_1.IDL.Text,
        'message_text': candid_1.IDL.Opt(candid_1.IDL.Text),
        'message_type': candid_1.IDL.Text,
        'chat_id': candid_1.IDL.Principal,
        'event_index': candid_1.IDL.Nat32,
        'thread_root_message_index': candid_1.IDL.Opt(candid_1.IDL.Nat32),
        'group_name': candid_1.IDL.Text,
        'crypto_transfer': candid_1.IDL.Opt(candid_1.IDL.Record({
            'recipient': candid_1.IDL.Principal,
            'ledger': candid_1.IDL.Principal,
            'recipient_username': candid_1.IDL.Opt(candid_1.IDL.Text),
            'amount': candid_1.IDL.Nat,
            'symbol': candid_1.IDL.Text,
        })),
        'message_index': candid_1.IDL.Nat32,
    }),
    'GroupMessageTipped': candid_1.IDL.Record({
        'tip': candid_1.IDL.Text,
        'tipped_by_display_name': candid_1.IDL.Opt(candid_1.IDL.Text),
        'group_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'message_event_index': candid_1.IDL.Nat32,
        'tipped_by': candid_1.IDL.Principal,
        'tipped_by_name': candid_1.IDL.Text,
        'chat_id': candid_1.IDL.Principal,
        'thread_root_message_index': candid_1.IDL.Opt(candid_1.IDL.Nat32),
        'group_name': candid_1.IDL.Text,
        'message_index': candid_1.IDL.Nat32,
    }),
    'AddedToChannel': candid_1.IDL.Record({
        'channel_id': candid_1.IDL.Nat,
        'community_id': candid_1.IDL.Principal,
        'added_by_name': candid_1.IDL.Text,
        'added_by': candid_1.IDL.Principal,
        'channel_name': candid_1.IDL.Text,
        'community_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'added_by_display_name': candid_1.IDL.Opt(candid_1.IDL.Text),
        'community_name': candid_1.IDL.Text,
        'channel_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
    }),
    'ChannelMessage': candid_1.IDL.Record({
        'channel_id': candid_1.IDL.Nat,
        'community_id': candid_1.IDL.Principal,
        'image_url': candid_1.IDL.Opt(candid_1.IDL.Text),
        'sender_display_name': candid_1.IDL.Opt(candid_1.IDL.Text),
        'sender': candid_1.IDL.Principal,
        'channel_name': candid_1.IDL.Text,
        'community_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'community_name': candid_1.IDL.Text,
        'sender_name': candid_1.IDL.Text,
        'message_text': candid_1.IDL.Opt(candid_1.IDL.Text),
        'message_type': candid_1.IDL.Text,
        'event_index': candid_1.IDL.Nat32,
        'thread_root_message_index': candid_1.IDL.Opt(candid_1.IDL.Nat32),
        'channel_avatar_id': candid_1.IDL.Opt(candid_1.IDL.Nat),
        'crypto_transfer': candid_1.IDL.Opt(candid_1.IDL.Record({
            'recipient': candid_1.IDL.Principal,
            'ledger': candid_1.IDL.Principal,
            'recipient_username': candid_1.IDL.Opt(candid_1.IDL.Text),
            'amount': candid_1.IDL.Nat,
            'symbol': candid_1.IDL.Text,
        })),
        'message_index': candid_1.IDL.Nat32,
    }),
});
