"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LARGE_GROUP_THRESHOLD = exports.ONE_YEAR = exports.ONE_MONTH = exports.ONE_WEEK = exports.ONE_DAY = exports.ONE_HOUR = exports.ONE_MINUTE_MILLIS = exports.MIN_DOWNLINK = exports.AIRDROP_BOT_AVATAR_URL = exports.AIRDROP_BOT_USERNAME = exports.AIRDROP_BOT_USER_ID = exports.OPENCHAT_BOT_AVATAR_URL = exports.OPENCHAT_BOT_USERNAME = exports.OPENCHAT_BOT_USER_ID = exports.OPENCHAT_VIDEO_CALL_AVATAR_URL = exports.OPENCHAT_VIDEO_CALL_USERNAME = exports.OPENCHAT_VIDEO_CALL_USER_ID = exports.MAX_MISSING = exports.MAX_ACTIVITY_EVENTS = exports.MAX_EVENTS = exports.MAX_MESSAGES = exports.ONLINE_THRESHOLD = void 0;
exports.ONLINE_THRESHOLD = 120;
exports.MAX_MESSAGES = 100;
exports.MAX_EVENTS = 500;
exports.MAX_ACTIVITY_EVENTS = 1000;
exports.MAX_MISSING = 30;
exports.OPENCHAT_VIDEO_CALL_USER_ID = "wp3oc-ig6b4-6xvef-yoj27-qt3kw-u2xmp-qbvuv-2grco-s2ndy-wv3ud-7qe";
exports.OPENCHAT_VIDEO_CALL_USERNAME = "VideoCallBot";
exports.OPENCHAT_VIDEO_CALL_AVATAR_URL = "/assets/video_call.svg";
exports.OPENCHAT_BOT_USER_ID = "zzyk3-openc-hatbo-tq7my-cai";
exports.OPENCHAT_BOT_USERNAME = "OpenChatBot";
exports.OPENCHAT_BOT_AVATAR_URL = "/assets/robot.svg";
exports.AIRDROP_BOT_USER_ID = process.env.AIRDROP_BOT_CANISTER;
exports.AIRDROP_BOT_USERNAME = "AirdropBot";
exports.AIRDROP_BOT_AVATAR_URL = "/assets/airdrop_bot.svg";
exports.MIN_DOWNLINK = 0.05;
exports.ONE_MINUTE_MILLIS = 60 * 1000;
exports.ONE_HOUR = 60 * exports.ONE_MINUTE_MILLIS;
exports.ONE_DAY = 24 * exports.ONE_HOUR;
exports.ONE_WEEK = exports.ONE_DAY * 7;
exports.ONE_MONTH = exports.ONE_WEEK * 4;
exports.ONE_YEAR = 365 * exports.ONE_DAY;
exports.LARGE_GROUP_THRESHOLD = 1000;
