export declare const ONLINE_THRESHOLD = 120;
export declare const MAX_MESSAGES = 100;
export declare const MAX_EVENTS = 500;
export declare const MAX_ACTIVITY_EVENTS = 1000;
export declare const MAX_MISSING = 30;
export declare const OPENCHAT_VIDEO_CALL_USER_ID = "wp3oc-ig6b4-6xvef-yoj27-qt3kw-u2xmp-qbvuv-2grco-s2ndy-wv3ud-7qe";
export declare const OPENCHAT_VIDEO_CALL_USERNAME = "VideoCallBot";
export declare const OPENCHAT_VIDEO_CALL_AVATAR_URL = "/assets/video_call.svg";
export declare const OPENCHAT_BOT_USER_ID = "zzyk3-openc-hatbo-tq7my-cai";
export declare const OPENCHAT_BOT_USERNAME = "OpenChatBot";
export declare const OPENCHAT_BOT_AVATAR_URL = "/assets/robot.svg";
export declare const AIRDROP_BOT_USER_ID: string;
export declare const AIRDROP_BOT_USERNAME = "AirdropBot";
export declare const AIRDROP_BOT_AVATAR_URL = "/assets/airdrop_bot.svg";
export declare const MIN_DOWNLINK = 0.05;
export declare const ONE_MINUTE_MILLIS: number;
export declare const ONE_HOUR: number;
export declare const ONE_DAY: number;
export declare const ONE_WEEK: number;
export declare const ONE_MONTH: number;
export declare const ONE_YEAR: number;
export declare const LARGE_GROUP_THRESHOLD = 1000;
