import type { HttpAgent, Identity } from "@dfinity/agent";
import { CandidService } from "../candidService";
import type { AgentConfig } from "../../config";
import type { AddMembersToChannelResponse, BlockCommunityUserResponse, CandidateChannel, ChangeCommunityRoleResponse, CommunityPermissions, EventWrapper, EventsResponse, MemberRole, Message, UnblockCommunityUserResponse, UpdateCommunityResponse, User, ChannelIdentifier, AddRemoveReactionResponse, CommunitySummaryResponse, CommunitySummaryUpdatesResponse, SendMessageResponse, UpdateGroupResponse, CreateGroupResponse, DeleteGroupResponse, PinMessageResponse, UnpinMessageResponse, GroupChatDetailsResponse, IndexRange, ChatEvent, EventsSuccessResult, EditMessageResponse, DeclineInvitationResponse, CommunityIdentifier, CommunityDetailsResponse, LeaveGroupResponse, DeleteMessageResponse, DeletedGroupMessageResponse, UndeleteMessageResponse, ThreadPreviewsResponse, ChangeRoleResponse, ChannelSummaryResponse, RegisterPollVoteResponse, ToggleMuteNotificationResponse, ExploreChannelsResponse, GroupChatIdentifier, ImportGroupResponse, RemoveMemberResponse, SearchGroupChatResponse, InviteCodeResponse, EnableInviteCodeResponse, DisableInviteCodeResponse, ResetInviteCodeResponse, RegisterProposalVoteResponse, CreateUserGroupResponse, UpdateUserGroupResponse, DeleteUserGroupsResponse, SetMemberDisplayNameResponse, UpdatedRules, FollowThreadResponse, OptionUpdate, ClaimPrizeResponse, OptionalChatPermissions, AcceptP2PSwapResponse, JoinVideoCallResponse, VideoCallPresence, SetVideoCallPresenceResponse, VideoCallParticipantsResponse, AccessGateConfig } from "openchat-shared";
import { type Database } from "../../utils/caching";
import type { CancelP2PSwapResponse } from "openchat-shared";
export declare class CommunityClient extends CandidService {
    private config;
    private communityId;
    private db;
    private inviteCode;
    constructor(identity: Identity, agent: HttpAgent, config: AgentConfig, communityId: string, db: Database, inviteCode: string | undefined);
    claimPrize(channelId: string, messageId: bigint): Promise<ClaimPrizeResponse>;
    addMembersToChannel(chatId: ChannelIdentifier, userIds: string[], username: string, displayName: string | undefined): Promise<AddMembersToChannelResponse>;
    addReaction(chatId: ChannelIdentifier, username: string, displayName: string | undefined, messageId: bigint, reaction: string, threadRootMessageIndex: number | undefined, newAchievement: boolean): Promise<AddRemoveReactionResponse>;
    blockUser(userId: string): Promise<BlockCommunityUserResponse>;
    changeChannelRole(chatId: ChannelIdentifier, userId: string, newRole: MemberRole): Promise<ChangeRoleResponse>;
    changeRole(userId: string, newRole: MemberRole): Promise<ChangeCommunityRoleResponse>;
    createChannel(channel: CandidateChannel): Promise<CreateGroupResponse>;
    declineInvitation(chatId: ChannelIdentifier): Promise<DeclineInvitationResponse>;
    deleteChannel(chatId: ChannelIdentifier): Promise<DeleteGroupResponse>;
    getDeletedMessage(chatId: ChannelIdentifier, messageId: bigint, threadRootMessageIndex?: number): Promise<DeletedGroupMessageResponse>;
    deleteMessages(chatId: ChannelIdentifier, messageIds: bigint[], threadRootMessageIndex: number | undefined, asPlatformModerator: boolean | undefined, newAchievement: boolean): Promise<DeleteMessageResponse>;
    disableInviteCode(): Promise<DisableInviteCodeResponse>;
    editMessage(chatId: ChannelIdentifier, message: Message, threadRootMessageIndex: number | undefined, blockLevelMarkdown: boolean | undefined, newAchievement: boolean): Promise<EditMessageResponse>;
    enableInviteCode(): Promise<EnableInviteCodeResponse>;
    events(chatId: ChannelIdentifier, eventIndexRange: IndexRange, startIndex: number, ascending: boolean, threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    eventsFromBackend(chatId: ChannelIdentifier, startIndex: number, ascending: boolean, threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined, maxEvents?: number): Promise<EventsResponse<ChatEvent>>;
    getCachedEventsByIndex(chatId: ChannelIdentifier, eventIndexes: number[], threadRootMessageIndex: number | undefined): Promise<[EventsSuccessResult<ChatEvent>, Set<number>]>;
    eventsByIndex(chatId: ChannelIdentifier, eventIndexes: number[], threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    private eventsByIndexFromBackend;
    eventsWindow(chatId: ChannelIdentifier, eventIndexRange: IndexRange, messageIndex: number, threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    private eventsWindowFromBackend;
    getMessagesByMessageIndex(chatId: ChannelIdentifier, messageIndexes: Set<number>, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<Message>>;
    private getMessagesByMessageIndexFromBackend;
    private handleMissingEvents;
    private setCachedEvents;
    getInviteCode(): Promise<InviteCodeResponse>;
    leaveChannel(chatId: ChannelIdentifier): Promise<LeaveGroupResponse>;
    localUserIndex(): Promise<string>;
    unpinMessage(chatId: ChannelIdentifier, messageIndex: number): Promise<UnpinMessageResponse>;
    pinMessage(chatId: ChannelIdentifier, messageIndex: number): Promise<PinMessageResponse>;
    removeMember(userId: string): Promise<RemoveMemberResponse>;
    removeMemberFromChannel(chatId: ChannelIdentifier, userId: string): Promise<RemoveMemberResponse>;
    removeReaction(chatId: ChannelIdentifier, messageId: bigint, reaction: string, threadRootMessageIndex: number | undefined): Promise<AddRemoveReactionResponse>;
    resetInviteCode(): Promise<ResetInviteCodeResponse>;
    searchChannel(chatId: ChannelIdentifier, maxResults: number, users: string[], searchTerm: string): Promise<SearchGroupChatResponse>;
    getCommunityDetails(id: CommunityIdentifier, communityLastUpdated: bigint): Promise<CommunityDetailsResponse>;
    private getCommunityDetailsFromBackend;
    private getCommunityDetailsUpdates;
    private getCommunityDetailsUpdatesFromBackend;
    getChannelDetails(chatId: ChannelIdentifier, chatLastUpdated: bigint): Promise<GroupChatDetailsResponse>;
    private getChannelDetailsFromBackend;
    private getChannelDetailsUpdates;
    private getChannelDetailsUpdatesFromBackend;
    sendMessage(chatId: ChannelIdentifier, senderName: string, senderDisplayName: string | undefined, mentioned: User[], event: EventWrapper<Message>, threadRootMessageIndex: number | undefined, communityRulesAccepted: number | undefined, channelRulesAccepted: number | undefined, messageFilterFailed: bigint | undefined, newAchievement: boolean, onRequestAccepted: () => void): Promise<[SendMessageResponse, Message]>;
    registerPollVote(chatId: ChannelIdentifier, messageIdx: number, answerIdx: number, voteType: "register" | "delete", threadRootMessageIndex: number | undefined, newAchievement: boolean): Promise<RegisterPollVoteResponse>;
    channelSummary(chatId: ChannelIdentifier): Promise<ChannelSummaryResponse>;
    importGroup(id: GroupChatIdentifier): Promise<ImportGroupResponse>;
    summary(): Promise<CommunitySummaryResponse>;
    exploreChannels(searchTerm: string | undefined, pageSize: number, pageIndex: number): Promise<ExploreChannelsResponse>;
    summaryUpdates(updatesSince: bigint): Promise<CommunitySummaryUpdatesResponse>;
    toggleMuteChannelNotifications(chatId: ChannelIdentifier | undefined, mute: boolean): Promise<ToggleMuteNotificationResponse>;
    unblockUser(userId: string): Promise<UnblockCommunityUserResponse>;
    undeleteMessage(chatId: ChannelIdentifier, messageId: bigint, threadRootMessageIndex?: number): Promise<UndeleteMessageResponse>;
    threadPreviews(chatId: ChannelIdentifier, threadRootMessageIndexes: number[], latestClientThreadUpdate: bigint | undefined): Promise<ThreadPreviewsResponse>;
    registerProposalVote(channelId: string, messageIdx: number, adopt: boolean): Promise<RegisterProposalVoteResponse>;
    updateChannel(chatId: ChannelIdentifier, name?: string, description?: string, rules?: UpdatedRules, permissions?: OptionalChatPermissions, avatar?: Uint8Array, eventsTimeToLiveMs?: OptionUpdate<bigint>, gateConfig?: AccessGateConfig, isPublic?: boolean, messagesVisibleToNonMembers?: boolean, externalUrl?: string): Promise<UpdateGroupResponse>;
    updateCommunity(name?: string, description?: string, rules?: UpdatedRules, permissions?: Partial<CommunityPermissions>, avatar?: Uint8Array, banner?: Uint8Array, gateConfig?: AccessGateConfig, isPublic?: boolean, primaryLanguage?: string): Promise<UpdateCommunityResponse>;
    createUserGroup(name: string, users: string[]): Promise<CreateUserGroupResponse>;
    updateUserGroup(userGroupId: number, name: string | undefined, usersToAdd: string[], usersToRemove: string[]): Promise<UpdateUserGroupResponse>;
    setMemberDisplayName(displayName: string | undefined, newAchievement: boolean): Promise<SetMemberDisplayNameResponse>;
    deleteUserGroups(userGroupIds: number[]): Promise<DeleteUserGroupsResponse>;
    followThread(channelId: string, threadRootMessageIndex: number, follow: boolean, newAchievement: boolean): Promise<FollowThreadResponse>;
    reportMessage(channelId: string, threadRootMessageIndex: number | undefined, messageId: bigint, deleteMessage: boolean): Promise<boolean>;
    acceptP2PSwap(channelId: string, threadRootMessageIndex: number | undefined, messageId: bigint, pin: string | undefined, newAchievement: boolean): Promise<AcceptP2PSwapResponse>;
    cancelP2PSwap(channelId: string, threadRootMessageIndex: number | undefined, messageId: bigint): Promise<CancelP2PSwapResponse>;
    joinVideoCall(channelId: string, messageId: bigint, newAchievement: boolean): Promise<JoinVideoCallResponse>;
    setVideoCallPresence(channelId: string, messageId: bigint, presence: VideoCallPresence, newAchievement: boolean): Promise<SetVideoCallPresenceResponse>;
    videoCallParticipants(channelId: string, messageId: bigint, updatesSince?: bigint): Promise<VideoCallParticipantsResponse>;
    cancelInvites(channelId: string | undefined, userIds: string[]): Promise<boolean>;
}
