import { type Identity } from "@dfinity/agent";
import { UserClient } from "./user/user.client";
import { GroupClient } from "./group/group.client";
import { LedgerClient } from "./ledger/ledger.client";
import { LedgerIndexClient } from "./ledgerIndex/ledgerIndex.client";
import type { AgentConfig } from "../config";
import type { AddRemoveReactionResponse, ArchiveChatResponse, BlobReference, BlockUserResponse, CandidateGroupChat, ChangeRoleResponse, ChatEvent, CheckUsernameResponse, CreatedUser, CreateGroupResponse, CurrentUserResponse, DeleteFrozenGroupResponse, DeleteGroupResponse, DeleteMessageResponse, DexId, DiamondMembershipFees, DisableInviteCodeResponse, EditMessageResponse, EnableInviteCodeResponse, EventsResponse, EventWrapper, GroupChatDetailsResponse, GroupChatSummary, GroupInvite, Rules, IndexRange, InviteCodeResponse, JoinGroupResponse, LeaveGroupResponse, ListNervousSystemFunctionsResponse, MarkReadRequest, MarkReadResponse, MemberRole, Message, OptionUpdate, PendingCryptocurrencyWithdrawal, PinChatResponse, PinMessageResponse, PublicProfile, RegisterPollVoteResponse, RegisterProposalVoteResponse, RegisterUserResponse, RemoveMemberResponse, ResetInviteCodeResponse, SearchDirectChatResponse, SearchGroupChatResponse, SendMessageResponse, SetBioResponse, SetUsernameResponse, StakeNeuronForSubmittingProposalsResponse, StorageStatus, SuspendUserResponse, SwapTokensResponse, ThreadPreview, ThreadSyncDetails, TokenSwapStatusResponse, ToggleMuteNotificationResponse, UnblockUserResponse, UndeleteMessageResponse, UnpinChatResponse, UnpinMessageResponse, UpdateGroupResponse, User, UserLookup, UsersArgs, UsersResponse, UserSummary, WithdrawCryptocurrencyResponse, FreezeGroupResponse, UnfreezeGroupResponse, UnsuspendUserResponse, ChatSummary, UpdatesResult, DeletedGroupMessageResponse, DeletedDirectMessageResponse, ClaimPrizeResponse, DiamondMembershipDuration, PayForDiamondMembershipResponse, AddHotGroupExclusionResponse, RemoveHotGroupExclusionResponse, SetCommunityModerationFlagsResponse, SetGroupUpgradeConcurrencyResponse, SetUserUpgradeConcurrencyResponse, UpdateMarketMakerConfigArgs, UpdateMarketMakerConfigResponse, ProposalVoteDetails, SetMessageReminderResponse, DeclineInvitationResponse, JoinCommunityResponse, GroupSearchResponse, ChatIdentifier, DirectChatIdentifier, GroupChatIdentifier, MessageContext, CommunitySummary, ExploreCommunitiesResponse, ChannelIdentifier, MultiUserChatIdentifier, CommunityIdentifier, CommunitySummaryResponse, ConvertToCommunityResponse, ExploreChannelsResponse, CommunityInvite, RegistryValue, PublicGroupSummaryResponse, SetDisplayNameResponse, CreateUserGroupResponse, UpdateUserGroupResponse, DeleteUserGroupsResponse, SetMemberDisplayNameResponse, UpdatedRules, FollowThreadResponse, CandidateProposal, SubmitProposalResponse, AccountTransactionResult, OptionalChatPermissions, CryptocurrencyDetails, ApproveTransferResponse, TokenExchangeRates, AcceptP2PSwapResponse, CancelP2PSwapResponse, ChatEventsArgs, ChatEventsResponse, JoinVideoCallResponse, AccessTokenType, UpdateBtcBalanceResponse, GenerateMagicLinkResponse, GetDelegationResponse, PrepareDelegationResponse, SiwePrepareLoginResponse, SiwsPrepareLoginResponse, VideoCallPresence, SetVideoCallPresenceResponse, VideoCallParticipantsResponse, AcceptedRules, VerifiedCredentialArgs, ChitEventsRequest, ChitEventsResponse, ChitState, SubmitProofOfUniquePersonhoodResponse, TopUpNeuronResponse, WalletConfig, ExternalAchievement, ChitLeaderboardResponse, AccessGateConfig, Verification, MessageActivityFeedResponse, MessageActivityEvent, FreezeCommunityResponse, UnfreezeCommunityResponse, ChannelSummaryResponse } from "openchat-shared";
import { Stream, MessageContextMap } from "openchat-shared";
import { AsyncMessageContextMap } from "../utils/messageContext";
import { CommunityClient } from "./community/community.client";
import { AnonUserClient } from "./user/anonUser.client";
import { TranslationsClient } from "./translations/translations.client";
import type { SetPinNumberResponse } from "openchat-shared";
import type { ClaimDailyChitResponse } from "openchat-shared";
export declare class OpenChatAgent extends EventTarget {
    private identity;
    private config;
    private _agent;
    private _userIndexClient;
    private _onlineClient;
    private _groupIndexClient;
    private _userClient?;
    private _notificationClient;
    private _proposalsBotClient;
    private _marketMakerClient;
    private _registryClient;
    private _dataClient;
    private _localUserIndexClients;
    private _ledgerClients;
    private _ledgerIndexClients;
    private _groupClients;
    private _communityClients;
    private _icpcoinsClient;
    private _signInWithEmailClient;
    private _signInWithEthereumClient;
    private _signInWithSolanaClient;
    private _dexesAgent;
    private _groupInvite;
    private _communityInvite;
    private _registryValue;
    private db;
    private _logger;
    translationsClient: TranslationsClient;
    constructor(identity: Identity, config: AgentConfig);
    private get principal();
    getAllCachedUsers(): Promise<UserLookup>;
    logError(message?: unknown, ...optionalParams: unknown[]): void;
    set groupInvite(value: GroupInvite);
    set communityInvite(value: CommunityInvite);
    createUserClient(userId: string): OpenChatAgent;
    communityClient(communityId: string): CommunityClient;
    getGroupClient(chatId: string): GroupClient;
    get userClient(): UserClient | AnonUserClient;
    getLedgerClient(ledger: string): LedgerClient;
    getLedgerIndexClient(ledgerIndex: string): LedgerIndexClient;
    private getLocalUserIndexClient;
    private getProvidedGroupInviteCode;
    private getProvidedCommunityInviteCode;
    private getCommunityReferral;
    editMessage(chatId: ChatIdentifier, msg: Message, threadRootMessageIndex: number | undefined, blockLevelMarkdown: boolean | undefined, newAchievement: boolean): Promise<EditMessageResponse>;
    sendMessage(messageContext: MessageContext, user: CreatedUser, mentioned: User[], event: EventWrapper<Message>, acceptedRules: AcceptedRules | undefined, messageFilterFailed: bigint | undefined, pin: string | undefined, newAchievement: boolean): Stream<"accepted" | [SendMessageResponse, Message]>;
    private sendChannelMessage;
    private sendGroupMessage;
    private editGroupMessage;
    private editChannelMessage;
    private sendDirectMessage;
    private editDirectMessage;
    createGroupChat(candidate: CandidateGroupChat): Promise<CreateGroupResponse>;
    updateGroup(chatId: MultiUserChatIdentifier, name?: string, desc?: string, rules?: UpdatedRules, permissions?: OptionalChatPermissions, avatar?: Uint8Array, eventsTimeToLive?: OptionUpdate<bigint>, gateConfig?: AccessGateConfig, isPublic?: boolean, messagesVisibleToNonMembers?: boolean, externalUrl?: string): Promise<UpdateGroupResponse>;
    inviteUsers(id: MultiUserChatIdentifier | CommunityIdentifier, userIds: string[], callerUsername: string): Promise<boolean>;
    chatEventsBatch(localUserIndex: string, requests: ChatEventsArgs[], cachePrimer: boolean): Promise<ChatEventsResponse[]>;
    chatEventsWindow(eventIndexRange: IndexRange, chatId: ChatIdentifier, messageIndex: number, threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    private directChatEventsWindow;
    chatEvents(chatId: ChatIdentifier, eventIndexRange: IndexRange, startIndex: number, ascending: boolean, threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    private directChatEvents;
    private directChatEventsByEventIndex;
    private channelEventsWindow;
    private groupChatEventsWindow;
    private channelEvents;
    private groupChatEvents;
    chatEventsByEventIndex(chatId: ChatIdentifier, eventIndexes: number[], threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    private channelEventsByEventIndex;
    private groupChatEventsByEventIndex;
    getDeletedGroupMessage(chatId: MultiUserChatIdentifier, messageId: bigint, threadRootMessageIndex?: number): Promise<DeletedGroupMessageResponse>;
    getDeletedDirectMessage(userId: string, messageId: bigint): Promise<DeletedDirectMessageResponse>;
    private rehydrateMessageContent;
    private findMissingEventIndexesByChat;
    private messagesFromEventsResponse;
    private resolveMissingIndexes;
    private rehydrateEvent;
    private rehydrateEventResponse;
    rehydrateUserSummary<T extends UserSummary>(userSummary: T): T;
    private rehydrateDataContent;
    rehydrateMessage(chatId: ChatIdentifier, message: EventWrapper<Message>, threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventWrapper<Message>>;
    searchUsers(searchTerm: string, maxResults?: number): Promise<UserSummary[]>;
    exploreChannels(id: CommunityIdentifier, searchTerm: string | undefined, pageIndex: number, pageSize?: number): Promise<ExploreChannelsResponse>;
    exploreCommunities(searchTerm: string | undefined, pageIndex: number, pageSize: number | undefined, flags: number, languages: string[]): Promise<ExploreCommunitiesResponse>;
    searchGroups(searchTerm: string, maxResults?: number): Promise<GroupSearchResponse>;
    searchGroupChat(chatId: MultiUserChatIdentifier, searchTerm: string, userIds: string[], maxResults?: number): Promise<SearchGroupChatResponse>;
    searchDirectChat(chatId: DirectChatIdentifier, searchTerm: string, maxResults?: number): Promise<SearchDirectChatResponse>;
    getUser(chitState: ChitState, userId: string, allowStale?: boolean): Promise<UserSummary | undefined>;
    getUsers(chitState: ChitState, users: UsersArgs, allowStale?: boolean): Promise<UsersResponse>;
    private getUpdatedPinnedChannels;
    private _getUpdates;
    getUpdates(initialLoad: boolean): Stream<UpdatesResult>;
    private removeExpiredLatestMessages;
    getCommunitySummary(communityId: string): Promise<CommunitySummaryResponse>;
    private hydrateChatState;
    hydrateCommunity(community: CommunitySummary): CommunitySummary;
    hydrateChatSummary<T extends ChatSummary>(chat: T): T;
    getCurrentUser(): Stream<CurrentUserResponse>;
    setModerationFlags(flags: number): Promise<boolean>;
    checkUsername(username: string): Promise<CheckUsernameResponse>;
    setUsername(userId: string, username: string): Promise<SetUsernameResponse>;
    setDisplayName(userId: string, displayName: string | undefined): Promise<SetDisplayNameResponse>;
    changeRole(chatId: MultiUserChatIdentifier, userId: string, newRole: MemberRole): Promise<ChangeRoleResponse>;
    deleteGroup(chatId: MultiUserChatIdentifier): Promise<DeleteGroupResponse>;
    removeMember(chatId: MultiUserChatIdentifier, userId: string): Promise<RemoveMemberResponse>;
    blockUserFromDirectChat(userId: string): Promise<BlockUserResponse>;
    blockUserFromGroupChat(chatId: MultiUserChatIdentifier, userId: string): Promise<BlockUserResponse>;
    unblockUserFromGroupChat(chatId: MultiUserChatIdentifier, userId: string): Promise<UnblockUserResponse>;
    unblockUserFromDirectChat(userId: string): Promise<UnblockUserResponse>;
    leaveGroup(chatId: MultiUserChatIdentifier): Promise<LeaveGroupResponse>;
    joinGroup(chatId: MultiUserChatIdentifier, credentialArgs: VerifiedCredentialArgs | undefined): Promise<JoinGroupResponse>;
    joinCommunity(id: CommunityIdentifier, credentialArgs: VerifiedCredentialArgs | undefined): Promise<JoinCommunityResponse>;
    markMessagesRead(request: MarkReadRequest): Promise<MarkReadResponse>;
    setUserAvatar(data: Uint8Array): Promise<BlobReference>;
    addReaction(chatId: ChatIdentifier, messageId: bigint, reaction: string, username: string, displayName: string | undefined, threadRootMessageIndex: number | undefined, newAchievement: boolean): Promise<AddRemoveReactionResponse>;
    removeReaction(chatId: ChatIdentifier, messageId: bigint, reaction: string, threadRootMessageIndex?: number): Promise<AddRemoveReactionResponse>;
    deleteMessage(chatId: ChatIdentifier, messageId: bigint, threadRootMessageIndex: number | undefined, asPlatformModerator: boolean | undefined, newAchievement: boolean): Promise<DeleteMessageResponse>;
    private deleteChannelMessage;
    private deleteGroupMessage;
    private deleteDirectMessage;
    undeleteMessage(chatId: ChatIdentifier, messageId: bigint, threadRootMessageIndex?: number): Promise<UndeleteMessageResponse>;
    lastOnline(userIds: string[]): Promise<Record<string, number>>;
    markAsOnline(): Promise<void>;
    subscriptionExists(p256dh_key: string): Promise<boolean>;
    pushSubscription(subscription: PushSubscriptionJSON): Promise<void>;
    removeSubscription(subscription: PushSubscriptionJSON): Promise<void>;
    toggleMuteNotifications(id: ChatIdentifier | CommunityIdentifier, muted: boolean): Promise<ToggleMuteNotificationResponse>;
    getGroupDetails(chatId: MultiUserChatIdentifier, chatLastUpdated: bigint): Promise<GroupChatDetailsResponse>;
    getPublicGroupSummary(chatId: GroupChatIdentifier): Promise<PublicGroupSummaryResponse>;
    getRecommendedGroups(exclusions: string[]): Promise<GroupChatSummary[]>;
    dismissRecommendation(chatId: GroupChatIdentifier): Promise<void>;
    getBio(userId?: string): Promise<string>;
    getPublicProfile(userId?: string): Promise<PublicProfile>;
    setBio(bio: string): Promise<SetBioResponse>;
    registerUser(username: string, referralCode: string | undefined): Promise<RegisterUserResponse>;
    getUserStorageLimits(): Promise<StorageStatus>;
    refreshAccountBalance(ledger: string, principal: string): Promise<bigint>;
    getAccountTransactions(ledgerIndex: string, principal: string, fromId?: bigint): Promise<AccountTransactionResult>;
    getGroupMessagesByMessageIndex(chatId: MultiUserChatIdentifier, messageIndexes: Set<number>, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<Message>>;
    pinMessage(chatId: MultiUserChatIdentifier, messageIndex: number): Promise<PinMessageResponse>;
    unpinMessage(chatId: MultiUserChatIdentifier, messageIndex: number): Promise<UnpinMessageResponse>;
    registerPollVote(chatId: MultiUserChatIdentifier, messageIdx: number, answerIdx: number, voteType: "register" | "delete", threadRootMessageIndex: number | undefined, newAchievement: boolean): Promise<RegisterPollVoteResponse>;
    withdrawCryptocurrency(domain: PendingCryptocurrencyWithdrawal, pin: string | undefined): Promise<WithdrawCryptocurrencyResponse>;
    getInviteCode(id: GroupChatIdentifier | CommunityIdentifier): Promise<InviteCodeResponse>;
    enableInviteCode(id: GroupChatIdentifier | CommunityIdentifier): Promise<EnableInviteCodeResponse>;
    disableInviteCode(id: GroupChatIdentifier | CommunityIdentifier): Promise<DisableInviteCodeResponse>;
    resetInviteCode(id: GroupChatIdentifier | CommunityIdentifier): Promise<ResetInviteCodeResponse>;
    pinChat(chatId: ChatIdentifier, favourite: boolean): Promise<PinChatResponse>;
    unpinChat(chatId: ChatIdentifier, favourite: boolean): Promise<UnpinChatResponse>;
    archiveChat(chatId: ChatIdentifier): Promise<ArchiveChatResponse>;
    unarchiveChat(chatId: ChatIdentifier): Promise<ArchiveChatResponse>;
    registerProposalVote(chatId: MultiUserChatIdentifier, messageIndex: number, adopt: boolean): Promise<RegisterProposalVoteResponse>;
    getProposalVoteDetails(governanceCanisterId: string, proposalId: bigint, isNns: boolean): Promise<ProposalVoteDetails>;
    listNervousSystemFunctions(snsGovernanceCanisterId: string): Promise<ListNervousSystemFunctionsResponse>;
    threadPreviews(threadsByChat: Map<string, [ThreadSyncDetails[], bigint | undefined]>): Promise<ThreadPreview[]>;
    private rehydrateThreadPreview;
    setCachedMessageFromNotification(chatId: ChatIdentifier, threadRootMessageIndex: number | undefined, message: EventWrapper<Message>): Promise<void>;
    freezeGroup(chatId: GroupChatIdentifier, reason: string | undefined): Promise<FreezeGroupResponse>;
    unfreezeGroup(chatId: GroupChatIdentifier): Promise<UnfreezeGroupResponse>;
    freezeCommunity(id: CommunityIdentifier, reason: string | undefined): Promise<FreezeCommunityResponse>;
    unfreezeCommunity(id: CommunityIdentifier): Promise<UnfreezeCommunityResponse>;
    deleteFrozenGroup(chatId: GroupChatIdentifier): Promise<DeleteFrozenGroupResponse>;
    addHotGroupExclusion(chatId: GroupChatIdentifier): Promise<AddHotGroupExclusionResponse>;
    removeHotGroupExclusion(chatId: GroupChatIdentifier): Promise<RemoveHotGroupExclusionResponse>;
    suspendUser(userId: string, reason: string): Promise<SuspendUserResponse>;
    unsuspendUser(userId: string): Promise<UnsuspendUserResponse>;
    loadFailedMessages(): Promise<Map<string, Record<number, EventWrapper<Message>>>>;
    deleteFailedMessage(chatId: ChatIdentifier, messageId: bigint, threadRootMessageIndex?: number): Promise<void>;
    claimPrize(chatId: MultiUserChatIdentifier, messageId: bigint): Promise<ClaimPrizeResponse>;
    payForDiamondMembership(userId: string, token: string, duration: DiamondMembershipDuration, recurring: boolean, expectedPriceE8s: bigint): Promise<PayForDiamondMembershipResponse>;
    setCommunityModerationFlags(communityId: string, flags: number): Promise<SetCommunityModerationFlagsResponse>;
    setGroupUpgradeConcurrency(value: number): Promise<SetGroupUpgradeConcurrencyResponse>;
    setCommunityUpgradeConcurrency(value: number): Promise<SetGroupUpgradeConcurrencyResponse>;
    setUserUpgradeConcurrency(value: number): Promise<SetUserUpgradeConcurrencyResponse>;
    markLocalGroupIndexFull(canisterId: string, full: boolean): Promise<boolean>;
    stakeNeuronForSubmittingProposals(governanceCanisterId: string, stake: bigint): Promise<StakeNeuronForSubmittingProposalsResponse>;
    topUpNeuronForSubmittingProposals(governanceCanisterId: string, amount: bigint): Promise<TopUpNeuronResponse>;
    updateMarketMakerConfig(config: UpdateMarketMakerConfigArgs): Promise<UpdateMarketMakerConfigResponse>;
    setMessageReminder(chatId: ChatIdentifier, eventIndex: number, remindAt: number, notes?: string, threadRootMessageIndex?: number): Promise<SetMessageReminderResponse>;
    cancelMessageReminder(reminderId: bigint): Promise<boolean>;
    declineInvitation(chatId: MultiUserChatIdentifier): Promise<DeclineInvitationResponse>;
    convertGroupToCommunity(chatId: GroupChatIdentifier, historyVisible: boolean, rules: Rules): Promise<ConvertToCommunityResponse>;
    getRegistry(): Stream<[RegistryValue, boolean]>;
    setCommunityIndexes(communityIndexes: Record<string, number>): Promise<boolean>;
    createUserGroup(communityId: string, name: string, userIds: string[]): Promise<CreateUserGroupResponse>;
    updateUserGroup(communityId: string, userGroupId: number, name: string | undefined, usersToAdd: string[], usersToRemove: string[]): Promise<UpdateUserGroupResponse>;
    setMemberDisplayName(communityId: string, display_name: string | undefined, newAchievement: boolean): Promise<SetMemberDisplayNameResponse>;
    deleteUserGroups(communityId: string, userGroupIds: number[]): Promise<DeleteUserGroupsResponse>;
    getCachePrimerTimestamps(): Promise<Record<string, bigint>>;
    followThread(chatId: ChatIdentifier, threadRootMessageIndex: number, follow: boolean, newAchievement: boolean): Promise<FollowThreadResponse>;
    submitProposal(governanceCanisterId: string, proposal: CandidateProposal, ledger: string, token: string, proposalRejectionFee: bigint, transactionFee: bigint): Promise<SubmitProposalResponse>;
    reportMessage(chatId: ChatIdentifier, threadRootMessageIndex: number | undefined, messageId: bigint, deleteMessage: boolean): Promise<boolean>;
    canSwap(tokenLedgers: Set<string>): Promise<Set<string>>;
    getTokenSwaps(inputTokenLedger: string, outputTokenLedgers: string[]): Promise<Record<string, DexId[]>>;
    getTokenSwapQuotes(inputTokenLedger: string, outputTokenLedger: string, amountIn: bigint): Promise<[DexId, bigint][]>;
    swapTokens(swapId: bigint, inputTokenDetails: CryptocurrencyDetails, outputTokenDetails: CryptocurrencyDetails, amountIn: bigint, minAmountOut: bigint, dex: DexId, pin: string | undefined): Promise<SwapTokensResponse>;
    tokenSwapStatus(swapId: bigint): Promise<TokenSwapStatusResponse>;
    private swapProviders;
    approveTransfer(spender: string, ledger: string, amount: bigint, expiresIn: bigint | undefined, pin: string | undefined): Promise<ApproveTransferResponse>;
    deleteDirectChat(userId: string, blockUser: boolean): Promise<boolean>;
    diamondMembershipFees(): Promise<DiamondMembershipFees[]>;
    setDiamondMembershipFees(fees: DiamondMembershipFees[]): Promise<boolean>;
    addRemoveSwapProvider(swapProvider: DexId, add: boolean): Promise<boolean>;
    addMessageFilter(regex: string): Promise<boolean>;
    removeMessageFilter(id: bigint): Promise<boolean>;
    setTokenEnabled(ledger: string, enabled: boolean): Promise<boolean>;
    exchangeRates(): Promise<Record<string, TokenExchangeRates>>;
    reportedMessages(userId: string | undefined): Promise<string>;
    acceptP2PSwap(chatId: ChatIdentifier, threadRootMessageIndex: number | undefined, messageId: bigint, pin: string | undefined, newAchievement: boolean): Promise<AcceptP2PSwapResponse>;
    cancelP2PSwap(chatId: ChatIdentifier, threadRootMessageIndex: number | undefined, messageId: bigint): Promise<CancelP2PSwapResponse>;
    videoCallParticipants(chatId: MultiUserChatIdentifier, messageId: bigint, updatesSince?: bigint): Promise<VideoCallParticipantsResponse>;
    joinVideoCall(chatId: ChatIdentifier, messageId: bigint, newAchievement: boolean): Promise<JoinVideoCallResponse>;
    setVideoCallPresence(chatId: MultiUserChatIdentifier, messageId: bigint, presence: VideoCallPresence, newAchievement: boolean): Promise<SetVideoCallPresenceResponse>;
    getAccessToken(chatId: ChatIdentifier, accessTokenType: AccessTokenType, localUserIndex: string): Promise<string | undefined>;
    getLocalUserIndexForUser(userId: string): Promise<string>;
    updateBtcBalance(userId: string): Promise<UpdateBtcBalanceResponse>;
    generateMagicLink(email: string, sessionKey: Uint8Array): Promise<GenerateMagicLinkResponse>;
    getSignInWithEmailDelegation(email: string, sessionKey: Uint8Array, expiration: bigint): Promise<GetDelegationResponse>;
    siwePrepareLogin(address: string): Promise<SiwePrepareLoginResponse>;
    siwsPrepareLogin(address: string): Promise<SiwsPrepareLoginResponse>;
    loginWithWallet(token: "eth" | "sol", address: string, signature: string, sessionKey: Uint8Array): Promise<PrepareDelegationResponse>;
    getDelegationWithWallet(token: "eth" | "sol", address: string, sessionKey: Uint8Array, expiration: bigint): Promise<GetDelegationResponse>;
    setPinNumber(verification: Verification, newPin: string | undefined): Promise<SetPinNumberResponse>;
    claimDailyChit(): Promise<ClaimDailyChitResponse>;
    chitLeaderboard(): Promise<ChitLeaderboardResponse>;
    chitEvents(req: ChitEventsRequest): Promise<ChitEventsResponse>;
    markAchievementsSeen(): Promise<void>;
    submitProofOfUniquePersonhood(iiPrincipal: string, credential: string): Promise<SubmitProofOfUniquePersonhoodResponse>;
    configureWallet(config: WalletConfig): Promise<void>;
    cancelInvites(id: MultiUserChatIdentifier | CommunityIdentifier, userIds: string[]): Promise<boolean>;
    clearCachedData(): Promise<void>;
    getExternalAchievements(): Promise<ExternalAchievement[]>;
    private mergeExternalAchievements;
    markActivityFeedRead(readUpTo: bigint): Promise<void>;
    messageActivityFeed(): Stream<MessageActivityFeedResponse>;
    hydrateActivityFeedEvents(activityEvents: MessageActivityEvent[], callback: (events: MessageActivityEvent[], final: boolean) => void): Promise<void>;
    getMessagesByMessageContext(eventIndexesByMessageContext: AsyncMessageContextMap<number>, activityEvents: MessageActivityEvent[], mode: "cached" | "missing"): Promise<[MessageActivityEvent[], MessageContextMap<Set<number>>]>;
    deleteUser(userId: string): Promise<boolean>;
    getChannelSummary(channelId: ChannelIdentifier): Promise<ChannelSummaryResponse>;
}
