import type { HttpAgent, Identity } from "@dfinity/agent";
import type { EventsResponse, Message, SendMessageResponse, RemoveMemberResponse, UpdateGroupResponse, AddRemoveReactionResponse, IndexRange, DeleteMessageResponse, UndeleteMessageResponse, EditMessageResponse, BlockUserResponse, ChangeRoleResponse, GroupChatDetailsResponse, UnblockUserResponse, MemberRole, PinMessageResponse, UnpinMessageResponse, RegisterPollVoteResponse, InviteCodeResponse, EnableInviteCodeResponse, DisableInviteCodeResponse, ResetInviteCodeResponse, ThreadPreviewsResponse, RegisterProposalVoteResponse, Rules, SearchGroupChatResponse, User, GroupCanisterSummaryResponse, GroupCanisterSummaryUpdatesResponse, DeletedGroupMessageResponse, EventWrapper, OptionUpdate, ClaimPrizeResponse, DeclineInvitationResponse, EventsSuccessResult, ChatEvent, GroupChatIdentifier, ConvertToCommunityResponse, PublicGroupSummaryResponse, UpdatedRules, FollowThreadResponse, OptionalChatPermissions, ToggleMuteNotificationResponse, AcceptP2PSwapResponse, JoinVideoCallResponse, SetVideoCallPresenceResponse, VideoCallPresence, VideoCallParticipantsResponse, AccessGateConfig } from "openchat-shared";
import { CandidService } from "../candidService";
import { type Database } from "../../utils/caching";
import type { AgentConfig } from "../../config";
import type { CancelP2PSwapResponse } from "openchat-shared";
export declare class GroupClient extends CandidService {
    private config;
    private chatId;
    private db;
    private inviteCode;
    constructor(identity: Identity, agent: HttpAgent, config: AgentConfig, chatId: GroupChatIdentifier, db: Database, inviteCode: string | undefined);
    summary(): Promise<GroupCanisterSummaryResponse>;
    summaryUpdates(updatesSince: bigint): Promise<GroupCanisterSummaryUpdatesResponse>;
    getCachedEventsByIndex(eventIndexes: number[], threadRootMessageIndex: number | undefined): Promise<[EventsSuccessResult<ChatEvent>, Set<number>]>;
    chatEventsByIndex(eventIndexes: number[], threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    private setCachedEvents;
    private handleMissingEvents;
    chatEventsByIndexFromBackend(eventIndexes: number[], threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    chatEventsWindow(eventIndexRange: IndexRange, messageIndex: number, threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined, maxEvents?: number): Promise<EventsResponse<ChatEvent>>;
    private chatEventsWindowFromBackend;
    chatEvents(eventIndexRange: IndexRange, startIndex: number, ascending: boolean, threadRootMessageIndex: number | undefined, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
    private chatEventsFromBackend;
    changeRole(userId: string, newRole: MemberRole): Promise<ChangeRoleResponse>;
    removeMember(userId: string): Promise<RemoveMemberResponse>;
    editMessage(message: Message, threadRootMessageIndex: number | undefined, blockLevelMarkdown: boolean | undefined, newAchievement: boolean): Promise<EditMessageResponse>;
    claimPrize(messageId: bigint): Promise<ClaimPrizeResponse>;
    sendMessage(senderName: string, senderDisplayName: string | undefined, mentioned: User[], event: EventWrapper<Message>, threadRootMessageIndex: number | undefined, rulesAccepted: number | undefined, messageFilterFailed: bigint | undefined, newAchievement: boolean, onRequestAccepted: () => void): Promise<[SendMessageResponse, Message]>;
    updateGroup(name?: string, description?: string, rules?: UpdatedRules, permissions?: OptionalChatPermissions, avatar?: Uint8Array, eventsTimeToLiveMs?: OptionUpdate<bigint>, gateConfig?: AccessGateConfig, isPublic?: boolean, messagesVisibleToNonMembers?: boolean): Promise<UpdateGroupResponse>;
    addReaction(messageId: bigint, reaction: string, username: string, displayName: string | undefined, threadRootMessageIndex: number | undefined, newAchievement: boolean): Promise<AddRemoveReactionResponse>;
    removeReaction(messageId: bigint, reaction: string, threadRootMessageIndex?: number): Promise<AddRemoveReactionResponse>;
    deleteMessage(messageId: bigint, threadRootMessageIndex: number | undefined, asPlatformModerator: boolean | undefined, newAchievement: boolean): Promise<DeleteMessageResponse>;
    undeleteMessage(messageId: bigint, threadRootMessageIndex?: number): Promise<UndeleteMessageResponse>;
    blockUser(userId: string): Promise<BlockUserResponse>;
    unblockUser(userId: string): Promise<UnblockUserResponse>;
    getGroupDetails(chatLastUpdated: bigint): Promise<GroupChatDetailsResponse>;
    private getGroupDetailsFromBackend;
    private getGroupDetailsUpdates;
    private getGroupDetailsUpdatesFromBackend;
    getPublicSummary(): Promise<PublicGroupSummaryResponse>;
    getMessagesByMessageIndex(messageIndexes: Set<number>, latestKnownUpdate: bigint | undefined): Promise<EventsResponse<Message>>;
    private getMessagesByMessageIndexFromBackend;
    getDeletedMessage(messageId: bigint, threadRootMessageIndex?: number): Promise<DeletedGroupMessageResponse>;
    pinMessage(messageIndex: number): Promise<PinMessageResponse>;
    unpinMessage(messageIndex: number): Promise<UnpinMessageResponse>;
    registerPollVote(messageIdx: number, answerIdx: number, voteType: "register" | "delete", threadRootMessageIndex: number | undefined, newAchievement: boolean): Promise<RegisterPollVoteResponse>;
    searchGroupChat(searchTerm: string, userIds: string[], maxResults: number): Promise<SearchGroupChatResponse>;
    getInviteCode(): Promise<InviteCodeResponse>;
    enableInviteCode(): Promise<EnableInviteCodeResponse>;
    disableInviteCode(): Promise<DisableInviteCodeResponse>;
    resetInviteCode(): Promise<ResetInviteCodeResponse>;
    threadPreviews(threadRootMessageIndexes: number[], latestClientThreadUpdate: bigint | undefined): Promise<ThreadPreviewsResponse>;
    registerProposalVote(messageIdx: number, adopt: boolean): Promise<RegisterProposalVoteResponse>;
    registerProposalVoteV2(messageIdx: number, adopt: boolean): Promise<RegisterProposalVoteResponse>;
    localUserIndex(): Promise<string>;
    declineInvitation(): Promise<DeclineInvitationResponse>;
    toggleMuteNotifications(mute: boolean): Promise<ToggleMuteNotificationResponse>;
    convertToCommunity(historyVisible: boolean, rules: Rules): Promise<ConvertToCommunityResponse>;
    followThread(threadRootMessageIndex: number, follow: boolean, newAchievement: boolean): Promise<FollowThreadResponse>;
    reportMessage(threadRootMessageIndex: number | undefined, messageId: bigint, deleteMessage: boolean): Promise<boolean>;
    acceptP2PSwap(threadRootMessageIndex: number | undefined, messageId: bigint, pin: string | undefined, newAchievement: boolean): Promise<AcceptP2PSwapResponse>;
    cancelP2PSwap(threadRootMessageIndex: number | undefined, messageId: bigint): Promise<CancelP2PSwapResponse>;
    joinVideoCall(messageId: bigint, newAchievement: boolean): Promise<JoinVideoCallResponse>;
    setVideoCallPresence(messageId: bigint, presence: VideoCallPresence, newAchievement: boolean): Promise<SetVideoCallPresenceResponse>;
    videoCallParticipants(messageId: bigint, updatesSince?: bigint): Promise<VideoCallParticipantsResponse>;
    cancelInvites(userIds: string[]): Promise<boolean>;
}
