import type { CommunityEventsResponse, CommunityMessagesByMessageIndexResponse, GroupBlockUserResponse, GroupCanisterGroupChatSummary as TGroupCanisterGroupChatSummary, GroupCanisterGroupChatSummaryUpdates as TGroupCanisterGroupChatSummaryUpdates, GroupConvertIntoCommunityResponse, GroupEventsResponse, GroupFollowThreadResponse, GroupMessagesByMessageIndexResponse, GroupRemoveParticipantResponse, GroupReportMessageResponse, GroupRole, GroupSendMessageResponse, GroupSummaryResponse, GroupSummaryUpdatesResponse, GroupUnblockUserResponse, GroupUnfollowThreadResponse, OptionalGroupPermissions as TOptionalGroupPermissions, UpdatedRules as TUpdatedRules, GroupMembershipUpdates as TGroupMembershipUpdates } from "../../typebox";
import type { ChatEvent, EventsResponse, SendMessageResponse, RemoveMemberResponse, BlockUserResponse, UnblockUserResponse, MemberRole, Message, GroupCanisterGroupChatSummary, GroupCanisterGroupChatSummaryUpdates, GroupCanisterSummaryResponse, GroupCanisterSummaryUpdatesResponse, ChatIdentifier, MultiUserChatIdentifier, ConvertToCommunityResponse, UpdatedRules, FollowThreadResponse, OptionalChatPermissions, GroupMembershipUpdates } from "openchat-shared";
import type { Principal } from "@dfinity/principal";
export declare function apiRole(role: MemberRole): GroupRole | undefined;
export declare function summaryResponse(value: GroupSummaryResponse): GroupCanisterSummaryResponse;
export declare function groupChatSummary(value: TGroupCanisterGroupChatSummary): GroupCanisterGroupChatSummary;
export declare function summaryUpdatesResponse(value: GroupSummaryUpdatesResponse): GroupCanisterSummaryUpdatesResponse;
export declare function groupMembershipUpdates(value: TGroupMembershipUpdates): GroupMembershipUpdates;
export declare function groupChatSummaryUpdates(value: TGroupCanisterGroupChatSummaryUpdates): GroupCanisterGroupChatSummaryUpdates;
export declare function apiOptionalGroupPermissions(permissions: OptionalChatPermissions): TOptionalGroupPermissions;
export declare function unblockUserResponse(value: GroupUnblockUserResponse): UnblockUserResponse;
export declare function blockUserResponse(value: GroupBlockUserResponse): BlockUserResponse;
export declare function sendMessageResponse(value: GroupSendMessageResponse): SendMessageResponse;
export declare function removeMemberResponse(value: GroupRemoveParticipantResponse): RemoveMemberResponse;
export declare function getMessagesByMessageIndexResponse(principal: Principal, value: GroupMessagesByMessageIndexResponse | CommunityMessagesByMessageIndexResponse, chatId: MultiUserChatIdentifier, latestKnownUpdatePreRequest: bigint | undefined): Promise<EventsResponse<Message>>;
export declare function getEventsResponse(principal: Principal, value: GroupEventsResponse | CommunityEventsResponse, chatId: ChatIdentifier, latestKnownUpdatePreRequest: bigint | undefined): Promise<EventsResponse<ChatEvent>>;
export declare function convertToCommunityResponse(value: GroupConvertIntoCommunityResponse): ConvertToCommunityResponse;
export declare function apiUpdatedRules(rules: UpdatedRules): TUpdatedRules;
export declare function followThreadResponse(value: GroupFollowThreadResponse | GroupUnfollowThreadResponse): FollowThreadResponse;
export declare function reportMessageResponse(value: GroupReportMessageResponse): boolean;
