import type { Message, ChatEvent, EventsSuccessResult, ThreadSummary, MessageContent, CryptocurrencyContent, CryptocurrencyTransfer, CompletedCryptocurrencyTransfer, FailedCryptocurrencyTransfer, ReplyContext, ChatPermissions, PermissionRole, PendingCryptocurrencyWithdrawal, Metrics, MemberRole, GroupSubtype, AccessGate, GroupChatSummary, GateCheckFailedReason, CommunityPermissionRole, CommunityPermissions, ChatIdentifier, AddRemoveReactionResponse, ChannelSummary, CommunitySummary, Mention, EventWrapper, UpdateGroupResponse, CreateGroupResponse, MultiUserChatIdentifier, DeleteGroupResponse, PinMessageResponse, UnpinMessageResponse, GroupChatDetailsResponse, Member, GroupChatDetailsUpdatesResponse, EditMessageResponse, DeclineInvitationResponse, LeaveGroupResponse, DeleteMessageResponse, DeletedGroupMessageResponse, UndeleteMessageResponse, ThreadPreview, ThreadPreviewsResponse, ChangeRoleResponse, RegisterPollVoteResponse, JoinGroupResponse, SearchGroupChatResponse, InviteCodeResponse, EnableInviteCodeResponse, DisableInviteCodeResponse, ThreadSyncDetails, RegisterProposalVoteResponse, UserGroupSummary, TipsReceived, PrizeContentInitial, ClaimPrizeResponse, ExpiredEventsRange, ExpiredMessagesRange, P2PSwapContentInitial, CancelP2PSwapResponse, JoinVideoCallResponse, VideoCallPresence, SetVideoCallPresenceResponse, VideoCallParticipantsResponse, UpdatedEvent, User, DexId, MessageMatch, AcceptP2PSwapResponse, AccessGateConfig, SetPinNumberResponse } from "openchat-shared";
import type { AccessGate as TAccessGate, AccessGateConfig as TAccessGateConfig, Chat as TChat, ChatEvent as TChatEvent, ChatMetrics as TChatMetrics, CommunityAcceptP2pSwapResponse, CommunityAddReactionResponse, CommunityCancelP2pSwapResponse, CommunityCanisterChannelSummary as TCommunityCanisterChannelSummary, CommunityCanisterCommunitySummary as TCommunityCanisterCommunitySummary, CommunityChangeChannelRoleResponse, CommunityClaimPrizeResponse, CommunityCreateChannelResponse, CommunityDeclineInvitationResponse, CommunityDeleteChannelResponse, CommunityDeleteMessagesResponse, CommunityDeletedMessageResponse, CommunityDisableInviteCodeResponse, CommunityEditMessageResponse, CommunityEnableInviteCodeResponse, CommunityInviteCodeResponse, CommunityLeaveChannelResponse, CommunityPermissionRole as TCommunityPermissionRole, CommunityPermissions as TCommunityPermissions, CommunityPinMessageResponse, CommunityRegisterPollVoteResponse, CommunityRegisterProposalVoteResponse, CommunityRemoveReactionResponse, CommunityRole as TCommunityRole, CommunitySearchChannelResponse, CommunitySelectedChannelInitialResponse, CommunitySelectedChannelUpdatesResponse, CommunitySetVideoCallPresenceResponse, CommunityThreadPreviewsResponse, CommunityUndeleteMessagesResponse, CommunityUpdateChannelResponse, CommunityVideoCallParticipantsResponse, CompletedCryptoTransaction as TCompletedCryptoTransaction, CryptoContent as TCryptoContent, CryptoTransaction as TCryptoTransaction, Cryptocurrency as TCryptocurrency, EventWrapperChatEvent as TEventWrapperChatEvent, EventWrapperMessage as TEventWrapperMessage, EventsResponse as TEventsResponse, ExchangeId as TExchangeId, FailedCryptoTransaction as TFailedCryptoTransaction, GateCheckFailedReason as TGateCheckFailedReason, GroupAcceptP2pSwapResponse, GroupAddReactionResponse, GroupCancelP2pSwapResponse, GroupCanisterGroupChatSummary as TGroupCanisterGroupChatSummary, GroupCanisterThreadDetails as TGroupCanisterThreadDetails, GroupChangeRoleResponse, GroupClaimPrizeResponse, GroupDeclineInvitiationResponse, GroupDeleteMessagesResponse, GroupDeletedMessageResponse, GroupDisableInviteCodeResponse, GroupEditMessageResponse, GroupEnableInviteCodeResponse, GroupInviteCodeResponse, GroupMember as TGroupMember, GroupPermissionRole as TGroupPermissionRole, GroupPermissions as TGroupPermissions, GroupPinMessageResponse, GroupRegisterPollVoteResponse, GroupRegisterProposalVoteResponse, GroupRemoveReactionResponse, GroupRole as TGroupRole, GroupSearchMessagesResponse, GroupSelectedInitialResponse, GroupSelectedUpdatesResponse, GroupSetVideoCallPresenceResponse, GroupSubtype as TGroupSubtype, GroupThreadPreviewsResponse, GroupUndeleteMessagesResponse, GroupUnpinMessageResponse, GroupUpdateGroupResponse, GroupVideoCallParticipantsResponse, HydratedMention as TMention, LocalUserIndexJoinGroupResponse, Message as TMessage, MessageContent as TMessageContent, MessageContentInitial as TMessageContentInitial, MessageMatch as TMessageMatch, MessagesResponse as TMessagesResponse, MultiUserChat as TMultiUserChat, P2PSwapContentInitial as TP2PSwapContentInitial, PrizeContentInitial as TPrizeContentInitial, ReplyContext as TReplyContext, SwapStatusError as TSwapStatusError, ThreadPreview as TThreadPreview, ThreadSummary as TThreadSummary, User as TUser, UserAcceptP2pSwapResponse, UserAddReactionResponse, UserCancelP2pSwapResponse, UserCreateGroupResponse, UserDeleteGroupResponse, UserEditMessageResponse, UserGroupSummary as TUserGroupSummary, UserJoinVideoCallResponse, UserLeaveGroupResponse, UserRemoveReactionResponse, UserSetPinNumberResponse, UserWithdrawCryptoArgs, VideoCallPresence as TVideoCallPresence } from "../../typebox";
export declare function eventsSuccessResponse(value: TEventsResponse): EventsSuccessResult<ChatEvent>;
export declare function eventWrapper(value: TEventWrapperChatEvent): EventWrapper<ChatEvent>;
export declare function event(value: TChatEvent): ChatEvent;
export declare function message(value: TMessage): Message;
export declare function tips(value: [Uint8Array, [Uint8Array, bigint][]][]): TipsReceived;
export declare function threadSummary(value: TThreadSummary): ThreadSummary;
export declare function messageContent(value: TMessageContent, sender: string): MessageContent;
export declare function apiUser(domain: User): TUser;
export declare function token(value: TCryptocurrency): string;
export declare function apiToken(token: string): TCryptocurrency;
export declare function completedCryptoTransfer(value: TCompletedCryptoTransaction, sender: string, recipient: string): CompletedCryptocurrencyTransfer;
export declare function failedCryptoTransfer(value: TFailedCryptoTransaction, recipient: string): FailedCryptocurrencyTransfer;
export declare function groupPermissions(value: TGroupPermissions): ChatPermissions;
export declare function communityPermissions(value: TCommunityPermissions): CommunityPermissions;
export declare function communityPermissionRole(value: TCommunityPermissionRole | TCommunityRole): CommunityPermissionRole;
export declare function apiCommunityPermissions(permissions: CommunityPermissions): TCommunityPermissions;
export declare function apiCommunityPermissionRole(permissionRole: CommunityPermissionRole): TCommunityPermissionRole;
export declare function apiGroupPermissions(permissions: ChatPermissions): TGroupPermissions;
export declare function apiPermissionRole(permissionRole: PermissionRole): TGroupPermissionRole;
export declare function permissionRole(value: TGroupPermissionRole): PermissionRole;
export declare function chatMetrics(value: TChatMetrics): Metrics;
export declare function memberRole(value: TGroupRole | TCommunityRole): MemberRole;
export declare function apiMultiUserChat(chatId: ChatIdentifier): TMultiUserChat;
export declare function apiReplyContextArgs(chatId: ChatIdentifier, domain: ReplyContext): TReplyContext;
export declare function apiMessageContent(domain: MessageContent): TMessageContentInitial;
export declare function apiMaybeAccessGateConfig(domain: AccessGateConfig): TAccessGateConfig | undefined;
export declare function apiMaybeAccessGate(domain: AccessGate): TAccessGate | undefined;
export declare function apiAccessGateConfig(domain: AccessGateConfig): TAccessGateConfig;
export declare function apiAccessGate(domain: AccessGate): TAccessGate;
export declare function credentialArguments(value: [string, {
    String: string;
} | {
    Int: number;
}][]): Record<string, string | number>;
export declare function accessGateConfig(value: TAccessGateConfig): AccessGateConfig;
export declare function accessGate(value: TAccessGate): AccessGate;
export declare function apiPrizeContentInitial(domain: PrizeContentInitial): TPrizeContentInitial;
export declare function apiP2PSwapContentInitial(domain: P2PSwapContentInitial): TP2PSwapContentInitial;
export declare function apiPendingCryptoContent(domain: CryptocurrencyContent): TCryptoContent;
export declare function apiPendingCryptoTransaction(domain: CryptocurrencyTransfer): TCryptoTransaction;
export declare function apiPendingCryptocurrencyWithdrawal(domain: PendingCryptocurrencyWithdrawal, pin: string | undefined): UserWithdrawCryptoArgs;
export declare function proposalVote(vote: number): boolean | undefined;
export declare function apiProposalVote(vote: boolean): number;
export declare function groupChatSummary(value: TGroupCanisterGroupChatSummary): GroupChatSummary;
export declare function communitySummary(value: TCommunityCanisterCommunitySummary): CommunitySummary;
export declare function userGroup(value: TUserGroupSummary): [number, UserGroupSummary];
export declare function communityChannelSummary(value: TCommunityCanisterChannelSummary, communityId: string): ChannelSummary;
export declare function threadSyncDetails(value: TGroupCanisterThreadDetails): ThreadSyncDetails;
export declare function updatedEvent([threadRootMessageIndex, eventIndex, timestamp]: [
    number | null,
    number,
    bigint
]): UpdatedEvent;
export declare function gateCheckFailedReason(value: TGateCheckFailedReason): GateCheckFailedReason;
export declare function addRemoveReactionResponse(value: UserAddReactionResponse | UserRemoveReactionResponse | GroupAddReactionResponse | GroupRemoveReactionResponse | CommunityAddReactionResponse | CommunityRemoveReactionResponse): AddRemoveReactionResponse;
export declare function groupSubtype(subtype: TGroupSubtype): GroupSubtype;
export declare function messagesSuccessResponse(value: TMessagesResponse): EventsSuccessResult<Message>;
export declare function messageEvent(value: TEventWrapperMessage): EventWrapper<Message>;
export declare function mention(value: TMention): Mention;
export declare function mentions(value: TMention[]): Mention[];
export declare function expiredEventsRange([start, end]: [number, number]): ExpiredEventsRange;
export declare function expiredMessagesRange([start, end]: [number, number]): ExpiredMessagesRange;
export declare function updateGroupResponse(value: GroupUpdateGroupResponse | CommunityUpdateChannelResponse): UpdateGroupResponse;
export declare function createGroupResponse(value: UserCreateGroupResponse | CommunityCreateChannelResponse, id: MultiUserChatIdentifier): CreateGroupResponse;
export declare function deleteGroupResponse(value: UserDeleteGroupResponse | CommunityDeleteChannelResponse): DeleteGroupResponse;
export declare function pinMessageResponse(value: GroupPinMessageResponse | CommunityPinMessageResponse): PinMessageResponse;
export declare function unpinMessageResponse(value: GroupUnpinMessageResponse | CommunityPinMessageResponse): UnpinMessageResponse;
export declare function groupDetailsResponse(value: GroupSelectedInitialResponse | CommunitySelectedChannelInitialResponse): GroupChatDetailsResponse;
export declare function groupDetailsUpdatesResponse(value: GroupSelectedUpdatesResponse | CommunitySelectedChannelUpdatesResponse): GroupChatDetailsUpdatesResponse;
export declare function member(value: TGroupMember): Member;
export declare function editMessageResponse(value: UserEditMessageResponse | GroupEditMessageResponse | CommunityEditMessageResponse): EditMessageResponse;
export declare function declineInvitationResponse(value: GroupDeclineInvitiationResponse | CommunityDeclineInvitationResponse): DeclineInvitationResponse;
export declare function leaveGroupResponse(value: UserLeaveGroupResponse | CommunityLeaveChannelResponse): LeaveGroupResponse;
export declare function deleteMessageResponse(value: GroupDeleteMessagesResponse | CommunityDeleteMessagesResponse): DeleteMessageResponse;
export declare function deletedMessageResponse(value: GroupDeletedMessageResponse | CommunityDeletedMessageResponse): DeletedGroupMessageResponse;
export declare function undeleteMessageResponse(value: GroupUndeleteMessagesResponse | CommunityUndeleteMessagesResponse): UndeleteMessageResponse;
export declare function threadPreviewsResponse(value: GroupThreadPreviewsResponse | CommunityThreadPreviewsResponse, chatId: ChatIdentifier, latestClientThreadUpdate: bigint | undefined): ThreadPreviewsResponse;
export declare function threadPreview(chatId: ChatIdentifier, value: TThreadPreview): ThreadPreview;
export declare function changeRoleResponse(value: GroupChangeRoleResponse | CommunityChangeChannelRoleResponse): ChangeRoleResponse;
export declare function registerPollVoteResponse(value: GroupRegisterPollVoteResponse | CommunityRegisterPollVoteResponse): RegisterPollVoteResponse;
export declare function apiChatIdentifier(chatId: ChatIdentifier): TChat;
export declare function joinGroupResponse(value: LocalUserIndexJoinGroupResponse): JoinGroupResponse;
export declare function searchGroupChatResponse(value: GroupSearchMessagesResponse | CommunitySearchChannelResponse, chatId: MultiUserChatIdentifier): SearchGroupChatResponse;
export declare function messageMatch(value: TMessageMatch, chatId: ChatIdentifier): MessageMatch;
export declare function inviteCodeResponse(value: GroupInviteCodeResponse | CommunityInviteCodeResponse): InviteCodeResponse;
export declare function enableOrResetInviteCodeResponse(value: GroupEnableInviteCodeResponse | CommunityEnableInviteCodeResponse): EnableInviteCodeResponse;
export declare function disableInviteCodeResponse(value: GroupDisableInviteCodeResponse | CommunityDisableInviteCodeResponse): DisableInviteCodeResponse;
export declare function registerProposalVoteResponse(value: GroupRegisterProposalVoteResponse | CommunityRegisterProposalVoteResponse): RegisterProposalVoteResponse;
export declare function claimPrizeResponse(value: GroupClaimPrizeResponse | CommunityClaimPrizeResponse): ClaimPrizeResponse;
export declare function statusError(value: TSwapStatusError): AcceptP2PSwapResponse & CancelP2PSwapResponse;
export declare function acceptP2PSwapResponse(value: UserAcceptP2pSwapResponse | GroupAcceptP2pSwapResponse | CommunityAcceptP2pSwapResponse): AcceptP2PSwapResponse;
export declare function cancelP2PSwapResponse(value: UserCancelP2pSwapResponse | GroupCancelP2pSwapResponse | CommunityCancelP2pSwapResponse): CancelP2PSwapResponse;
export declare function joinVideoCallResponse(value: UserJoinVideoCallResponse | GroupSetVideoCallPresenceResponse | CommunitySetVideoCallPresenceResponse): JoinVideoCallResponse;
export declare function apiVideoCallPresence(domain: VideoCallPresence): TVideoCallPresence;
export declare function setVideoCallPresence(value: GroupSetVideoCallPresenceResponse | CommunitySetVideoCallPresenceResponse): SetVideoCallPresenceResponse;
export declare function videoCallParticipantsResponse(value: GroupVideoCallParticipantsResponse | CommunityVideoCallParticipantsResponse): VideoCallParticipantsResponse;
export declare function setPinNumberResponse(value: UserSetPinNumberResponse): SetPinNumberResponse;
export declare function apiDexId(dex: DexId): TExchangeId;
