import type { ChatEvent, Metrics, ChatSummary, EventWrapper, IndexRange, MemberRole, MessageContent, ChatIdentifier, MessageContext, ChatListScope, CryptocurrencyDetails, VersionedRules, AccountTransaction, AttachmentContent, MessagePermission, P2PSwapStatus, AcceptP2PSwapResponse, CancelP2PSwapResponse } from "../domain";
import type { MessageFormatter } from "./i18n";
export declare function userIdsFromTransactions(transactions: AccountTransaction[]): Set<string>;
export declare function userIdsFromEvents(events: EventWrapper<ChatEvent>[]): Set<string>;
export declare function getContentAsFormattedText(formatter: MessageFormatter, content: MessageContent, cryptoLookup: Record<string, CryptocurrencyDetails>): string;
export declare function getContentAsText(content: MessageContent): string | undefined;
export declare function indexRangeForChat(chat: ChatSummary): IndexRange;
export declare function getMinVisibleEventIndex(chat: ChatSummary): number;
export declare function getDisplayDate(chat: ChatSummary): bigint;
export declare function compareChats(a: ChatSummary, b: ChatSummary): number;
export declare function emptyChatMetrics(): Metrics;
export declare function emptyRules(): VersionedRules;
export declare function compareRoles(a: MemberRole, b: MemberRole): number;
export declare function routeForMessage(scope: ChatListScope["kind"], ctx: MessageContext, messageIndex: number): string;
export declare function routeForMessageContext(scope: ChatListScope["kind"], { chatId, threadRootMessageIndex }: MessageContext, open?: boolean): string;
export declare function routeForChatIdentifier(scope: ChatListScope["kind"], id: ChatIdentifier): string;
export declare function chatIdentifierToString(chatId: ChatIdentifier): string;
export declare function contentTypeToPermission(contentType: AttachmentContent["kind"]): MessagePermission;
export declare function mapAcceptP2PSwapResponseToStatus(response: AcceptP2PSwapResponse, userId: string): P2PSwapStatus;
export declare function mapCancelP2PSwapResponseToStatus(response: CancelP2PSwapResponse): P2PSwapStatus;
