import type { CheckUsernameResponse, SetUsernameResponse, CurrentUserResponse, UserSummary, SuspendUserResponse, UnsuspendUserResponse, DiamondMembershipDuration, DiamondMembershipFees, PayForDiamondMembershipResponse, SetDisplayNameResponse, DiamondMembershipStatus, CurrentUserSummary, UsersApiResponse, UserSummaryUpdate, SubmitProofOfUniquePersonhoodResponse, ExternalAchievementsResponse, ChitLeaderboardResponse } from "openchat-shared";
import type { CurrentUserSummary as TCurrentUserSummary, DiamondMembershipPlanDuration as TDiamondMembershipPlanDuration, DiamondMembershipStatus as TDiamondMembershipStatus, UserIndexCheckUsernameResponse, UserIndexChitLeaderboardResponse, UserIndexCurrentUserResponse, UserIndexDiamondMembershipFeesResponse, UserIndexPayForDiamondMembershipResponse, UserIndexSearchResponse, UserIndexSetDisplayNameResponse, UserIndexSetUsernameResponse, UserIndexSubmitProofOfUniquePersonhoodResponse, UserIndexSuspendUserResponse, UserIndexUnsuspendUserResponse, UserIndexUserRegistrationCanisterResponse, UserIndexUsersResponse, UserSummary as TUserSummary, UserSummaryV2 as TUserSummaryV2, UserIndexExternalAchievementsResponse } from "../../typebox";
export declare function userSearchResponse(value: UserIndexSearchResponse): UserSummary[];
export declare function usersApiResponse(value: UserIndexUsersResponse): UsersApiResponse;
export declare function currentUserSummary(value: TCurrentUserSummary, timestamp: bigint): CurrentUserSummary;
export declare function userSummaryUpdate(value: TUserSummaryV2): UserSummaryUpdate;
export declare function userSummary(value: TUserSummary, timestamp: bigint): UserSummary;
export declare function diamondStatus(value: TDiamondMembershipStatus): DiamondMembershipStatus["kind"];
export declare function userRegistrationCanisterResponse(value: UserIndexUserRegistrationCanisterResponse): string;
export declare function currentUserResponse(value: UserIndexCurrentUserResponse): CurrentUserResponse;
export declare function checkUsernameResponse(value: UserIndexCheckUsernameResponse): CheckUsernameResponse;
export declare function setUsernameResponse(value: UserIndexSetUsernameResponse): SetUsernameResponse;
export declare function setDisplayNameResponse(value: UserIndexSetDisplayNameResponse): SetDisplayNameResponse;
export declare function suspendUserResponse(value: UserIndexSuspendUserResponse): SuspendUserResponse;
export declare function unsuspendUserResponse(value: UserIndexUnsuspendUserResponse): UnsuspendUserResponse;
export declare function payForDiamondMembershipResponse(duration: DiamondMembershipDuration, value: UserIndexPayForDiamondMembershipResponse): PayForDiamondMembershipResponse;
export declare function apiJsonDiamondDuration(domain: DiamondMembershipDuration): TDiamondMembershipPlanDuration;
export declare function diamondMembershipFeesResponse(value: UserIndexDiamondMembershipFeesResponse): DiamondMembershipFees[];
export declare function chitLeaderboardResponse(value: UserIndexChitLeaderboardResponse): ChitLeaderboardResponse;
export declare function submitProofOfUniquePersonhoodResponse(value: UserIndexSubmitProofOfUniquePersonhoodResponse): SubmitProofOfUniquePersonhoodResponse;
export declare function externalAchievementsResponse(value: UserIndexExternalAchievementsResponse): ExternalAchievementsResponse;
